package com.arcusys.learn.persistence.liferay.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
* The base model interface for the LFActivityStateTree service. Represents a row in the &quot;Learn_LFActivityStateTree&quot; database table, with each column mapped to a property of this class.
*
* <p>
    * This interface and its corresponding implementation {@link com.arcusys.learn.persistence.liferay.model.impl.LFActivityStateTreeModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.arcusys.learn.persistence.liferay.model.impl.LFActivityStateTreeImpl}.
    * </p>
*
* @author Brian Wing Shun Chan
* @see LFActivityStateTree
* @see com.arcusys.learn.persistence.liferay.model.impl.LFActivityStateTreeImpl
* @see com.arcusys.learn.persistence.liferay.model.impl.LFActivityStateTreeModelImpl
* @generated
*/
public interface LFActivityStateTreeModel extends BaseModel<LFActivityStateTree> {
    /*
    * NOTE FOR DEVELOPERS:
    *
    * Never modify or reference this interface directly. All methods that expect a l f activity state tree model instance should use the {@link LFActivityStateTree} interface instead.
    */

    /**
    * Returns the primary key of this l f activity state tree.
    *
    * @return the primary key of this l f activity state tree
    */
    public long getPrimaryKey();

    /**
    * Sets the primary key of this l f activity state tree.
    *
    * @param primaryKey the primary key of this l f activity state tree
    */
    public void setPrimaryKey(long primaryKey);

    /**
    * Returns the ID of this l f activity state tree.
    *
    * @return the ID of this l f activity state tree
    */
    public long getId();

    /**
        * Sets the ID of this l f activity state tree.
    *
    * @param id the ID of this l f activity state tree
    */
    public void setId(long id);

    /**
    * Returns the current activity i d of this l f activity state tree.
    *
    * @return the current activity i d of this l f activity state tree
    */
    @AutoEscape
    public String getCurrentActivityID();

    /**
        * Sets the current activity i d of this l f activity state tree.
    *
    * @param currentActivityID the current activity i d of this l f activity state tree
    */
    public void setCurrentActivityID(String currentActivityID);

    /**
    * Returns the suspended activity i d of this l f activity state tree.
    *
    * @return the suspended activity i d of this l f activity state tree
    */
    @AutoEscape
    public String getSuspendedActivityID();

    /**
        * Sets the suspended activity i d of this l f activity state tree.
    *
    * @param suspendedActivityID the suspended activity i d of this l f activity state tree
    */
    public void setSuspendedActivityID(String suspendedActivityID);

    /**
    * Returns the attempt i d of this l f activity state tree.
    *
    * @return the attempt i d of this l f activity state tree
    */
    public Integer getAttemptID();

    /**
        * Sets the attempt i d of this l f activity state tree.
    *
    * @param attemptID the attempt i d of this l f activity state tree
    */
    public void setAttemptID(Integer attemptID);

    public boolean isNew();

    public void setNew(boolean n);

    public boolean isCachedModel();

    public void setCachedModel(boolean cachedModel);

    public boolean isEscapedModel();

    public Serializable getPrimaryKeyObj();

    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    public ExpandoBridge getExpandoBridge();

    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    public Object clone();

    public int compareTo(LFActivityStateTree lfActivityStateTree);

    public int hashCode();

    public CacheModel<LFActivityStateTree> toCacheModel();

    public LFActivityStateTree toEscapedModel();

    public String toString();

    public String toXmlString();
}
