package com.arcusys.learn.persistence.liferay.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.math.BigDecimal;

/**
* The base model interface for the LFAnswer service. Represents a row in the &quot;Learn_LFAnswer&quot; database table, with each column mapped to a property of this class.
*
* <p>
    * This interface and its corresponding implementation {@link com.arcusys.learn.persistence.liferay.model.impl.LFAnswerModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.arcusys.learn.persistence.liferay.model.impl.LFAnswerImpl}.
    * </p>
*
* @author Brian Wing Shun Chan
* @see LFAnswer
* @see com.arcusys.learn.persistence.liferay.model.impl.LFAnswerImpl
* @see com.arcusys.learn.persistence.liferay.model.impl.LFAnswerModelImpl
* @generated
*/
public interface LFAnswerModel extends BaseModel<LFAnswer> {
    /*
    * NOTE FOR DEVELOPERS:
    *
    * Never modify or reference this interface directly. All methods that expect a l f answer model instance should use the {@link LFAnswer} interface instead.
    */

    /**
    * Returns the primary key of this l f answer.
    *
    * @return the primary key of this l f answer
    */
    public long getPrimaryKey();

    /**
    * Sets the primary key of this l f answer.
    *
    * @param primaryKey the primary key of this l f answer
    */
    public void setPrimaryKey(long primaryKey);

    /**
    * Returns the ID of this l f answer.
    *
    * @return the ID of this l f answer
    */
    public long getId();

    /**
        * Sets the ID of this l f answer.
    *
    * @param id the ID of this l f answer
    */
    public void setId(long id);

    /**
    * Returns the description of this l f answer.
    *
    * @return the description of this l f answer
    */
    @AutoEscape
    public String getDescription();

    /**
        * Sets the description of this l f answer.
    *
    * @param description the description of this l f answer
    */
    public void setDescription(String description);

    /**
    * Returns the correct of this l f answer.
    *
    * @return the correct of this l f answer
    */
    public boolean getCorrect();

    /**
    * Returns <code>true</code> if this l f answer is correct.
    *
    * @return <code>true</code> if this l f answer is correct; <code>false</code> otherwise
    */
    public boolean isCorrect();

    /**
        * Sets whether this l f answer is correct.
    *
    * @param correct the correct of this l f answer
    */
    public void setCorrect(boolean correct);

    /**
    * Returns the question ID of this l f answer.
    *
    * @return the question ID of this l f answer
    */
    public Integer getQuestionId();

    /**
        * Sets the question ID of this l f answer.
    *
    * @param questionId the question ID of this l f answer
    */
    public void setQuestionId(Integer questionId);

    /**
    * Returns the range from of this l f answer.
    *
    * @return the range from of this l f answer
    */
    public BigDecimal getRangeFrom();

    /**
        * Sets the range from of this l f answer.
    *
    * @param rangeFrom the range from of this l f answer
    */
    public void setRangeFrom(BigDecimal rangeFrom);

    /**
    * Returns the range to of this l f answer.
    *
    * @return the range to of this l f answer
    */
    public BigDecimal getRangeTo();

    /**
        * Sets the range to of this l f answer.
    *
    * @param rangeTo the range to of this l f answer
    */
    public void setRangeTo(BigDecimal rangeTo);

    /**
    * Returns the matching text of this l f answer.
    *
    * @return the matching text of this l f answer
    */
    @AutoEscape
    public String getMatchingText();

    /**
        * Sets the matching text of this l f answer.
    *
    * @param matchingText the matching text of this l f answer
    */
    public void setMatchingText(String matchingText);

    /**
    * Returns the answer position of this l f answer.
    *
    * @return the answer position of this l f answer
    */
    public Integer getAnswerPosition();

    /**
        * Sets the answer position of this l f answer.
    *
    * @param answerPosition the answer position of this l f answer
    */
    public void setAnswerPosition(Integer answerPosition);

    /**
    * Returns the answer type of this l f answer.
    *
    * @return the answer type of this l f answer
    */
    public Integer getAnswerType();

    /**
        * Sets the answer type of this l f answer.
    *
    * @param answerType the answer type of this l f answer
    */
    public void setAnswerType(Integer answerType);

    public boolean isNew();

    public void setNew(boolean n);

    public boolean isCachedModel();

    public void setCachedModel(boolean cachedModel);

    public boolean isEscapedModel();

    public Serializable getPrimaryKeyObj();

    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    public ExpandoBridge getExpandoBridge();

    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    public Object clone();

    public int compareTo(LFAnswer lfAnswer);

    public int hashCode();

    public CacheModel<LFAnswer> toCacheModel();

    public LFAnswer toEscapedModel();

    public String toString();

    public String toXmlString();
}
