package com.arcusys.learn.persistence.liferay.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the LFPackageScopeRule service. Represents a row in the &quot;Learn_LFPackageScopeRule&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.arcusys.learn.persistence.liferay.model.impl.LFPackageScopeRuleModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.arcusys.learn.persistence.liferay.model.impl.LFPackageScopeRuleImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LFPackageScopeRule
 * @see com.arcusys.learn.persistence.liferay.model.impl.LFPackageScopeRuleImpl
 * @see com.arcusys.learn.persistence.liferay.model.impl.LFPackageScopeRuleModelImpl
 * @generated
 */
public interface LFPackageScopeRuleModel extends BaseModel<LFPackageScopeRule> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a l f package scope rule model instance should use the {@link LFPackageScopeRule} interface instead.
     */

    /**
     * Returns the primary key of this l f package scope rule.
     *
     * @return the primary key of this l f package scope rule
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this l f package scope rule.
     *
     * @param primaryKey the primary key of this l f package scope rule
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the ID of this l f package scope rule.
     *
     * @return the ID of this l f package scope rule
     */
    public long getId();

    /**
     * Sets the ID of this l f package scope rule.
     *
     * @param id the ID of this l f package scope rule
     */
    public void setId(long id);

    /**
     * Returns the package i d of this l f package scope rule.
     *
     * @return the package i d of this l f package scope rule
     */
    public Integer getPackageID();

    /**
     * Sets the package i d of this l f package scope rule.
     *
     * @param packageID the package i d of this l f package scope rule
     */
    public void setPackageID(Integer packageID);

    /**
     * Returns the scope of this l f package scope rule.
     *
     * @return the scope of this l f package scope rule
     */
    @AutoEscape
    public String getScope();

    /**
     * Sets the scope of this l f package scope rule.
     *
     * @param scope the scope of this l f package scope rule
     */
    public void setScope(String scope);

    /**
     * Returns the scope i d of this l f package scope rule.
     *
     * @return the scope i d of this l f package scope rule
     */
    @AutoEscape
    public String getScopeID();

    /**
     * Sets the scope i d of this l f package scope rule.
     *
     * @param scopeID the scope i d of this l f package scope rule
     */
    public void setScopeID(String scopeID);

    /**
     * Returns the visibility of this l f package scope rule.
     *
     * @return the visibility of this l f package scope rule
     */
    public Boolean getVisibility();

    /**
     * Sets the visibility of this l f package scope rule.
     *
     * @param visibility the visibility of this l f package scope rule
     */
    public void setVisibility(Boolean visibility);

    /**
     * Returns the is default of this l f package scope rule.
     *
     * @return the is default of this l f package scope rule
     */
    public Boolean getIsDefault();

    /**
     * Sets the is default of this l f package scope rule.
     *
     * @param isDefault the is default of this l f package scope rule
     */
    public void setIsDefault(Boolean isDefault);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(LFPackageScopeRule lfPackageScopeRule);

    @Override
    public int hashCode();

    @Override
    public CacheModel<LFPackageScopeRule> toCacheModel();

    @Override
    public LFPackageScopeRule toEscapedModel();

    @Override
    public LFPackageScopeRule toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
