package com.arcusys.learn.persistence.liferay.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
* The base model interface for the LFTincanLrsSubStatement service. Represents a row in the &quot;Learn_LFTincanLrsSubStatement&quot; database table, with each column mapped to a property of this class.
*
* <p>
    * This interface and its corresponding implementation {@link com.arcusys.learn.persistence.liferay.model.impl.LFTincanLrsSubStatementModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.arcusys.learn.persistence.liferay.model.impl.LFTincanLrsSubStatementImpl}.
    * </p>
*
* @author Brian Wing Shun Chan
* @see LFTincanLrsSubStatement
* @see com.arcusys.learn.persistence.liferay.model.impl.LFTincanLrsSubStatementImpl
* @see com.arcusys.learn.persistence.liferay.model.impl.LFTincanLrsSubStatementModelImpl
* @generated
*/
public interface LFTincanLrsSubStatementModel extends BaseModel<LFTincanLrsSubStatement> {
    /*
    * NOTE FOR DEVELOPERS:
    *
    * Never modify or reference this interface directly. All methods that expect a l f tincan lrs sub statement model instance should use the {@link LFTincanLrsSubStatement} interface instead.
    */

    /**
    * Returns the primary key of this l f tincan lrs sub statement.
    *
    * @return the primary key of this l f tincan lrs sub statement
    */
    public long getPrimaryKey();

    /**
    * Sets the primary key of this l f tincan lrs sub statement.
    *
    * @param primaryKey the primary key of this l f tincan lrs sub statement
    */
    public void setPrimaryKey(long primaryKey);

    /**
    * Returns the ID of this l f tincan lrs sub statement.
    *
    * @return the ID of this l f tincan lrs sub statement
    */
    public long getId();

    /**
        * Sets the ID of this l f tincan lrs sub statement.
    *
    * @param id the ID of this l f tincan lrs sub statement
    */
    public void setId(long id);

    /**
    * Returns the actor i d of this l f tincan lrs sub statement.
    *
    * @return the actor i d of this l f tincan lrs sub statement
    */
    public Integer getActorID();

    /**
        * Sets the actor i d of this l f tincan lrs sub statement.
    *
    * @param actorID the actor i d of this l f tincan lrs sub statement
    */
    public void setActorID(Integer actorID);

    /**
    * Returns the verb i d of this l f tincan lrs sub statement.
    *
    * @return the verb i d of this l f tincan lrs sub statement
    */
    @AutoEscape
    public String getVerbID();

    /**
        * Sets the verb i d of this l f tincan lrs sub statement.
    *
    * @param verbID the verb i d of this l f tincan lrs sub statement
    */
    public void setVerbID(String verbID);

    /**
    * Returns the verb display of this l f tincan lrs sub statement.
    *
    * @return the verb display of this l f tincan lrs sub statement
    */
    @AutoEscape
    public String getVerbDisplay();

    /**
        * Sets the verb display of this l f tincan lrs sub statement.
    *
    * @param verbDisplay the verb display of this l f tincan lrs sub statement
    */
    public void setVerbDisplay(String verbDisplay);

    /**
    * Returns the obj type of this l f tincan lrs sub statement.
    *
    * @return the obj type of this l f tincan lrs sub statement
    */
    @AutoEscape
    public String getObjType();

    /**
        * Sets the obj type of this l f tincan lrs sub statement.
    *
    * @param objType the obj type of this l f tincan lrs sub statement
    */
    public void setObjType(String objType);

    /**
    * Returns the obj i d of this l f tincan lrs sub statement.
    *
    * @return the obj i d of this l f tincan lrs sub statement
    */
    public Integer getObjID();

    /**
        * Sets the obj i d of this l f tincan lrs sub statement.
    *
    * @param objID the obj i d of this l f tincan lrs sub statement
    */
    public void setObjID(Integer objID);

    public boolean isNew();

    public void setNew(boolean n);

    public boolean isCachedModel();

    public void setCachedModel(boolean cachedModel);

    public boolean isEscapedModel();

    public Serializable getPrimaryKeyObj();

    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    public ExpandoBridge getExpandoBridge();

    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    public Object clone();

    public int compareTo(LFTincanLrsSubStatement lfTincanLrsSubStatement);

    public int hashCode();

    public CacheModel<LFTincanLrsSubStatement> toCacheModel();

    public LFTincanLrsSubStatement toEscapedModel();

    public String toString();

    public String toXmlString();
}
