package com.arcusys.learn.persistence.liferay.model.impl;

import com.arcusys.learn.persistence.liferay.model.LFActivity;
import com.arcusys.learn.persistence.liferay.service.LFActivityLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the LFActivity service. Represents a row in the &quot;Learn_LFActivity&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LFActivityImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LFActivityImpl
 * @see com.arcusys.learn.persistence.liferay.model.LFActivity
 * @generated
 */
public abstract class LFActivityBaseImpl extends LFActivityModelImpl
    implements LFActivity {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a l f activity model instance should use the {@link LFActivity} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            LFActivityLocalServiceUtil.addLFActivity(this);
        } else {
            LFActivityLocalServiceUtil.updateLFActivity(this);
        }
    }
}
