package com.arcusys.learn.persistence.liferay.model.impl;

import com.arcusys.learn.persistence.liferay.model.LFCertificateUser;
import com.arcusys.learn.persistence.liferay.model.LFCertificateUserModel;
import com.arcusys.learn.persistence.liferay.service.persistence.LFCertificateUserPK;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the LFCertificateUser service. Represents a row in the &quot;Learn_LFCertificateUser&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.arcusys.learn.persistence.liferay.model.LFCertificateUserModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LFCertificateUserImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LFCertificateUserImpl
 * @see com.arcusys.learn.persistence.liferay.model.LFCertificateUser
 * @see com.arcusys.learn.persistence.liferay.model.LFCertificateUserModel
 * @generated
 */
public class LFCertificateUserModelImpl extends BaseModelImpl<LFCertificateUser>
    implements LFCertificateUserModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a l f certificate user model instance should use the {@link com.arcusys.learn.persistence.liferay.model.LFCertificateUser} interface instead.
     */
    public static final String TABLE_NAME = "Learn_LFCertificateUser";
    public static final Object[][] TABLE_COLUMNS = {
            { "certificateID", Types.BIGINT },
            { "userID", Types.BIGINT },
            { "attachedDate", Types.TIMESTAMP }
        };
    public static final String TABLE_SQL_CREATE = "create table Learn_LFCertificateUser (certificateID LONG not null,userID LONG not null,attachedDate DATE null,primary key (certificateID, userID))";
    public static final String TABLE_SQL_DROP = "drop table Learn_LFCertificateUser";
    public static final String ORDER_BY_JPQL = " ORDER BY lfCertificateUser.id.certificateID ASC, lfCertificateUser.id.userID ASC";
    public static final String ORDER_BY_SQL = " ORDER BY Learn_LFCertificateUser.certificateID ASC, Learn_LFCertificateUser.userID ASC";
    public static final String DATA_SOURCE = "liferayDataSource";
    public static final String SESSION_FACTORY = "liferaySessionFactory";
    public static final String TX_MANAGER = "liferayTransactionManager";
    public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.entity.cache.enabled.com.arcusys.learn.persistence.liferay.model.LFCertificateUser"),
            false);
    public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.finder.cache.enabled.com.arcusys.learn.persistence.liferay.model.LFCertificateUser"),
            false);
    public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.column.bitmask.enabled.com.arcusys.learn.persistence.liferay.model.LFCertificateUser"),
            true);
    public static long CERTIFICATEID_COLUMN_BITMASK = 1L;
    public static long USERID_COLUMN_BITMASK = 2L;
    public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
                "lock.expiration.time.com.arcusys.learn.persistence.liferay.model.LFCertificateUser"));
    private static ClassLoader _classLoader = LFCertificateUser.class.getClassLoader();
    private static Class<?>[] _escapedModelInterfaces = new Class[] {
            LFCertificateUser.class
        };
    private Long _certificateID;
    private Long _originalCertificateID;
    private boolean _setOriginalCertificateID;
    private Long _userID;
    private Long _originalUserID;
    private boolean _setOriginalUserID;
    private Date _attachedDate;
    private long _columnBitmask;
    private LFCertificateUser _escapedModel;

    public LFCertificateUserModelImpl() {
    }

    @Override
    public LFCertificateUserPK getPrimaryKey() {
        return new LFCertificateUserPK(_certificateID, _userID);
    }

    @Override
    public void setPrimaryKey(LFCertificateUserPK primaryKey) {
        setCertificateID(primaryKey.certificateID);
        setUserID(primaryKey.userID);
    }

    @Override
    public Serializable getPrimaryKeyObj() {
        return new LFCertificateUserPK(_certificateID, _userID);
    }

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj) {
        setPrimaryKey((LFCertificateUserPK) primaryKeyObj);
    }

    @Override
    public Class<?> getModelClass() {
        return LFCertificateUser.class;
    }

    @Override
    public String getModelClassName() {
        return LFCertificateUser.class.getName();
    }

    @Override
    public Map<String, Object> getModelAttributes() {
        Map<String, Object> attributes = new HashMap<String, Object>();

        attributes.put("certificateID", getCertificateID());
        attributes.put("userID", getUserID());
        attributes.put("attachedDate", getAttachedDate());

        return attributes;
    }

    @Override
    public void setModelAttributes(Map<String, Object> attributes) {
        Long certificateID = (Long) attributes.get("certificateID");

        if (certificateID != null) {
            setCertificateID(certificateID);
        }

        Long userID = (Long) attributes.get("userID");

        if (userID != null) {
            setUserID(userID);
        }

        Date attachedDate = (Date) attributes.get("attachedDate");

        if (attachedDate != null) {
            setAttachedDate(attachedDate);
        }
    }

    @Override
    public Long getCertificateID() {
        return _certificateID;
    }

    @Override
    public void setCertificateID(Long certificateID) {
        _columnBitmask |= CERTIFICATEID_COLUMN_BITMASK;

        if (!_setOriginalCertificateID) {
            _setOriginalCertificateID = true;

            _originalCertificateID = _certificateID;
        }

        _certificateID = certificateID;
    }

    public Long getOriginalCertificateID() {
        return _originalCertificateID;
    }

    @Override
    public Long getUserID() {
        return _userID;
    }

    @Override
    public void setUserID(Long userID) {
        _columnBitmask |= USERID_COLUMN_BITMASK;

        if (!_setOriginalUserID) {
            _setOriginalUserID = true;

            _originalUserID = _userID;
        }

        _userID = userID;
    }

    public Long getOriginalUserID() {
        return _originalUserID;
    }

    @Override
    public Date getAttachedDate() {
        return _attachedDate;
    }

    @Override
    public void setAttachedDate(Date attachedDate) {
        _attachedDate = attachedDate;
    }

    public long getColumnBitmask() {
        return _columnBitmask;
    }

    @Override
    public LFCertificateUser toEscapedModel() {
        if (_escapedModel == null) {
            _escapedModel = (LFCertificateUser) ProxyUtil.newProxyInstance(_classLoader,
                    _escapedModelInterfaces, new AutoEscapeBeanHandler(this));
        }

        return _escapedModel;
    }

    @Override
    public Object clone() {
        LFCertificateUserImpl lfCertificateUserImpl = new LFCertificateUserImpl();

        lfCertificateUserImpl.setCertificateID(getCertificateID());
        lfCertificateUserImpl.setUserID(getUserID());
        lfCertificateUserImpl.setAttachedDate(getAttachedDate());

        lfCertificateUserImpl.resetOriginalValues();

        return lfCertificateUserImpl;
    }

    @Override
    public int compareTo(LFCertificateUser lfCertificateUser) {
        LFCertificateUserPK primaryKey = lfCertificateUser.getPrimaryKey();

        return getPrimaryKey().compareTo(primaryKey);
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }

        if (!(obj instanceof LFCertificateUser)) {
            return false;
        }

        LFCertificateUser lfCertificateUser = (LFCertificateUser) obj;

        LFCertificateUserPK primaryKey = lfCertificateUser.getPrimaryKey();

        if (getPrimaryKey().equals(primaryKey)) {
            return true;
        } else {
            return false;
        }
    }

    @Override
    public int hashCode() {
        return getPrimaryKey().hashCode();
    }

    @Override
    public void resetOriginalValues() {
        LFCertificateUserModelImpl lfCertificateUserModelImpl = this;

        lfCertificateUserModelImpl._originalCertificateID = lfCertificateUserModelImpl._certificateID;

        lfCertificateUserModelImpl._setOriginalCertificateID = false;

        lfCertificateUserModelImpl._originalUserID = lfCertificateUserModelImpl._userID;

        lfCertificateUserModelImpl._setOriginalUserID = false;

        lfCertificateUserModelImpl._columnBitmask = 0;
    }

    @Override
    public CacheModel<LFCertificateUser> toCacheModel() {
        LFCertificateUserCacheModel lfCertificateUserCacheModel = new LFCertificateUserCacheModel();

        lfCertificateUserCacheModel.certificateID = getCertificateID();

        lfCertificateUserCacheModel.userID = getUserID();

        Date attachedDate = getAttachedDate();

        if (attachedDate != null) {
            lfCertificateUserCacheModel.attachedDate = attachedDate.getTime();
        } else {
            lfCertificateUserCacheModel.attachedDate = Long.MIN_VALUE;
        }

        return lfCertificateUserCacheModel;
    }

    @Override
    public String toString() {
        StringBundler sb = new StringBundler(7);

        sb.append("{certificateID=");
        sb.append(getCertificateID());
        sb.append(", userID=");
        sb.append(getUserID());
        sb.append(", attachedDate=");
        sb.append(getAttachedDate());
        sb.append("}");

        return sb.toString();
    }

    @Override
    public String toXmlString() {
        StringBundler sb = new StringBundler(13);

        sb.append("<model><model-name>");
        sb.append(
            "com.arcusys.learn.persistence.liferay.model.LFCertificateUser");
        sb.append("</model-name>");

        sb.append(
            "<column><column-name>certificateID</column-name><column-value><![CDATA[");
        sb.append(getCertificateID());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>userID</column-name><column-value><![CDATA[");
        sb.append(getUserID());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>attachedDate</column-name><column-value><![CDATA[");
        sb.append(getAttachedDate());
        sb.append("]]></column-value></column>");

        sb.append("</model>");

        return sb.toString();
    }
}
