package com.arcusys.learn.persistence.liferay.model.impl;

import com.arcusys.learn.persistence.liferay.model.LFCertificateActivity;
import com.arcusys.learn.persistence.liferay.model.LFCertificateActivityModel;
import com.arcusys.learn.persistence.liferay.service.persistence.LFCertificateActivityPK;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the LFCertificateActivity service. Represents a row in the &quot;Learn_LFCertificateActivity&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.arcusys.learn.persistence.liferay.model.LFCertificateActivityModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LFCertificateActivityImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LFCertificateActivityImpl
 * @see com.arcusys.learn.persistence.liferay.model.LFCertificateActivity
 * @see com.arcusys.learn.persistence.liferay.model.LFCertificateActivityModel
 * @generated
 */
public class LFCertificateActivityModelImpl extends BaseModelImpl<LFCertificateActivity>
    implements LFCertificateActivityModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a l f certificate activity model instance should use the {@link com.arcusys.learn.persistence.liferay.model.LFCertificateActivity} interface instead.
     */
    public static final String TABLE_NAME = "Learn_LFCertificateActivity";
    public static final Object[][] TABLE_COLUMNS = {
            { "certificateID", Types.BIGINT },
            { "activityName", Types.VARCHAR },
            { "datacount", Types.INTEGER },
            { "periodType", Types.VARCHAR },
            { "period", Types.INTEGER }
        };
    public static final String TABLE_SQL_CREATE = "create table Learn_LFCertificateActivity (certificateID LONG not null,activityName VARCHAR(75) not null,datacount INTEGER null,periodType VARCHAR(75) null,period INTEGER null,primary key (certificateID, activityName))";
    public static final String TABLE_SQL_DROP = "drop table Learn_LFCertificateActivity";
    public static final String ORDER_BY_JPQL = " ORDER BY lfCertificateActivity.id.certificateID ASC, lfCertificateActivity.id.activityName ASC";
    public static final String ORDER_BY_SQL = " ORDER BY Learn_LFCertificateActivity.certificateID ASC, Learn_LFCertificateActivity.activityName ASC";
    public static final String DATA_SOURCE = "liferayDataSource";
    public static final String SESSION_FACTORY = "liferaySessionFactory";
    public static final String TX_MANAGER = "liferayTransactionManager";
    public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.entity.cache.enabled.com.arcusys.learn.persistence.liferay.model.LFCertificateActivity"),
            false);
    public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.finder.cache.enabled.com.arcusys.learn.persistence.liferay.model.LFCertificateActivity"),
            false);
    public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.column.bitmask.enabled.com.arcusys.learn.persistence.liferay.model.LFCertificateActivity"),
            true);
    public static long ACTIVITYNAME_COLUMN_BITMASK = 1L;
    public static long CERTIFICATEID_COLUMN_BITMASK = 2L;
    public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
                "lock.expiration.time.com.arcusys.learn.persistence.liferay.model.LFCertificateActivity"));
    private static ClassLoader _classLoader = LFCertificateActivity.class.getClassLoader();
    private static Class<?>[] _escapedModelInterfaces = new Class[] {
            LFCertificateActivity.class
        };
    private Long _certificateID;
    private Long _originalCertificateID;
    private boolean _setOriginalCertificateID;
    private String _activityName;
    private String _originalActivityName;
    private Integer _datacount;
    private String _periodType;
    private Integer _period;
    private long _columnBitmask;
    private LFCertificateActivity _escapedModel;

    public LFCertificateActivityModelImpl() {
    }

    @Override
    public LFCertificateActivityPK getPrimaryKey() {
        return new LFCertificateActivityPK(_certificateID, _activityName);
    }

    @Override
    public void setPrimaryKey(LFCertificateActivityPK primaryKey) {
        setCertificateID(primaryKey.certificateID);
        setActivityName(primaryKey.activityName);
    }

    @Override
    public Serializable getPrimaryKeyObj() {
        return new LFCertificateActivityPK(_certificateID, _activityName);
    }

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj) {
        setPrimaryKey((LFCertificateActivityPK) primaryKeyObj);
    }

    @Override
    public Class<?> getModelClass() {
        return LFCertificateActivity.class;
    }

    @Override
    public String getModelClassName() {
        return LFCertificateActivity.class.getName();
    }

    @Override
    public Map<String, Object> getModelAttributes() {
        Map<String, Object> attributes = new HashMap<String, Object>();

        attributes.put("certificateID", getCertificateID());
        attributes.put("activityName", getActivityName());
        attributes.put("datacount", getDatacount());
        attributes.put("periodType", getPeriodType());
        attributes.put("period", getPeriod());

        return attributes;
    }

    @Override
    public void setModelAttributes(Map<String, Object> attributes) {
        Long certificateID = (Long) attributes.get("certificateID");

        if (certificateID != null) {
            setCertificateID(certificateID);
        }

        String activityName = (String) attributes.get("activityName");

        if (activityName != null) {
            setActivityName(activityName);
        }

        Integer datacount = (Integer) attributes.get("datacount");

        if (datacount != null) {
            setDatacount(datacount);
        }

        String periodType = (String) attributes.get("periodType");

        if (periodType != null) {
            setPeriodType(periodType);
        }

        Integer period = (Integer) attributes.get("period");

        if (period != null) {
            setPeriod(period);
        }
    }

    @Override
    public Long getCertificateID() {
        return _certificateID;
    }

    @Override
    public void setCertificateID(Long certificateID) {
        _columnBitmask |= CERTIFICATEID_COLUMN_BITMASK;

        if (!_setOriginalCertificateID) {
            _setOriginalCertificateID = true;

            _originalCertificateID = _certificateID;
        }

        _certificateID = certificateID;
    }

    public Long getOriginalCertificateID() {
        return _originalCertificateID;
    }

    @Override
    public String getActivityName() {
        return _activityName;
    }

    @Override
    public void setActivityName(String activityName) {
        _columnBitmask |= ACTIVITYNAME_COLUMN_BITMASK;

        if (_originalActivityName == null) {
            _originalActivityName = _activityName;
        }

        _activityName = activityName;
    }

    public String getOriginalActivityName() {
        return _originalActivityName;
    }

    @Override
    public Integer getDatacount() {
        return _datacount;
    }

    @Override
    public void setDatacount(Integer datacount) {
        _datacount = datacount;
    }

    @Override
    public String getPeriodType() {
        return _periodType;
    }

    @Override
    public void setPeriodType(String periodType) {
        _periodType = periodType;
    }

    @Override
    public Integer getPeriod() {
        return _period;
    }

    @Override
    public void setPeriod(Integer period) {
        _period = period;
    }

    public long getColumnBitmask() {
        return _columnBitmask;
    }

    @Override
    public LFCertificateActivity toEscapedModel() {
        if (_escapedModel == null) {
            _escapedModel = (LFCertificateActivity) ProxyUtil.newProxyInstance(_classLoader,
                    _escapedModelInterfaces, new AutoEscapeBeanHandler(this));
        }

        return _escapedModel;
    }

    @Override
    public Object clone() {
        LFCertificateActivityImpl lfCertificateActivityImpl = new LFCertificateActivityImpl();

        lfCertificateActivityImpl.setCertificateID(getCertificateID());
        lfCertificateActivityImpl.setActivityName(getActivityName());
        lfCertificateActivityImpl.setDatacount(getDatacount());
        lfCertificateActivityImpl.setPeriodType(getPeriodType());
        lfCertificateActivityImpl.setPeriod(getPeriod());

        lfCertificateActivityImpl.resetOriginalValues();

        return lfCertificateActivityImpl;
    }

    @Override
    public int compareTo(LFCertificateActivity lfCertificateActivity) {
        LFCertificateActivityPK primaryKey = lfCertificateActivity.getPrimaryKey();

        return getPrimaryKey().compareTo(primaryKey);
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }

        if (!(obj instanceof LFCertificateActivity)) {
            return false;
        }

        LFCertificateActivity lfCertificateActivity = (LFCertificateActivity) obj;

        LFCertificateActivityPK primaryKey = lfCertificateActivity.getPrimaryKey();

        if (getPrimaryKey().equals(primaryKey)) {
            return true;
        } else {
            return false;
        }
    }

    @Override
    public int hashCode() {
        return getPrimaryKey().hashCode();
    }

    @Override
    public void resetOriginalValues() {
        LFCertificateActivityModelImpl lfCertificateActivityModelImpl = this;

        lfCertificateActivityModelImpl._originalCertificateID = lfCertificateActivityModelImpl._certificateID;

        lfCertificateActivityModelImpl._setOriginalCertificateID = false;

        lfCertificateActivityModelImpl._originalActivityName = lfCertificateActivityModelImpl._activityName;

        lfCertificateActivityModelImpl._columnBitmask = 0;
    }

    @Override
    public CacheModel<LFCertificateActivity> toCacheModel() {
        LFCertificateActivityCacheModel lfCertificateActivityCacheModel = new LFCertificateActivityCacheModel();

        lfCertificateActivityCacheModel.certificateID = getCertificateID();

        lfCertificateActivityCacheModel.activityName = getActivityName();

        String activityName = lfCertificateActivityCacheModel.activityName;

        if ((activityName != null) && (activityName.length() == 0)) {
            lfCertificateActivityCacheModel.activityName = null;
        }

        lfCertificateActivityCacheModel.datacount = getDatacount();

        lfCertificateActivityCacheModel.periodType = getPeriodType();

        String periodType = lfCertificateActivityCacheModel.periodType;

        if ((periodType != null) && (periodType.length() == 0)) {
            lfCertificateActivityCacheModel.periodType = null;
        }

        lfCertificateActivityCacheModel.period = getPeriod();

        return lfCertificateActivityCacheModel;
    }

    @Override
    public String toString() {
        StringBundler sb = new StringBundler(11);

        sb.append("{certificateID=");
        sb.append(getCertificateID());
        sb.append(", activityName=");
        sb.append(getActivityName());
        sb.append(", datacount=");
        sb.append(getDatacount());
        sb.append(", periodType=");
        sb.append(getPeriodType());
        sb.append(", period=");
        sb.append(getPeriod());
        sb.append("}");

        return sb.toString();
    }

    @Override
    public String toXmlString() {
        StringBundler sb = new StringBundler(19);

        sb.append("<model><model-name>");
        sb.append(
            "com.arcusys.learn.persistence.liferay.model.LFCertificateActivity");
        sb.append("</model-name>");

        sb.append(
            "<column><column-name>certificateID</column-name><column-value><![CDATA[");
        sb.append(getCertificateID());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>activityName</column-name><column-value><![CDATA[");
        sb.append(getActivityName());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>datacount</column-name><column-value><![CDATA[");
        sb.append(getDatacount());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>periodType</column-name><column-value><![CDATA[");
        sb.append(getPeriodType());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>period</column-name><column-value><![CDATA[");
        sb.append(getPeriod());
        sb.append("]]></column-value></column>");

        sb.append("</model>");

        return sb.toString();
    }
}
