package com.arcusys.learn.persistence.liferay.model.impl;

import com.arcusys.learn.persistence.liferay.model.LFLRSToActivitySetting;
import com.arcusys.learn.persistence.liferay.model.LFLRSToActivitySettingModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the LFLRSToActivitySetting service. Represents a row in the &quot;Learn_LFLRSToActivitySetting&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.arcusys.learn.persistence.liferay.model.LFLRSToActivitySettingModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LFLRSToActivitySettingImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LFLRSToActivitySettingImpl
 * @see com.arcusys.learn.persistence.liferay.model.LFLRSToActivitySetting
 * @see com.arcusys.learn.persistence.liferay.model.LFLRSToActivitySettingModel
 * @generated
 */
public class LFLRSToActivitySettingModelImpl extends BaseModelImpl<LFLRSToActivitySetting>
    implements LFLRSToActivitySettingModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a l f l r s to activity setting model instance should use the {@link com.arcusys.learn.persistence.liferay.model.LFLRSToActivitySetting} interface instead.
     */
    public static final String TABLE_NAME = "Learn_LFLRSToActivitySetting";
    public static final Object[][] TABLE_COLUMNS = {
            { "id_", Types.BIGINT },
            { "courseID", Types.INTEGER },
            { "title", Types.VARCHAR },
            { "activityFilter", Types.VARCHAR },
            { "verbFilter", Types.VARCHAR }
        };
    public static final String TABLE_SQL_CREATE = "create table Learn_LFLRSToActivitySetting (id_ LONG not null primary key,courseID INTEGER null,title VARCHAR(75) null,activityFilter VARCHAR(1000) null,verbFilter VARCHAR(1000) null)";
    public static final String TABLE_SQL_DROP = "drop table Learn_LFLRSToActivitySetting";
    public static final String ORDER_BY_JPQL = " ORDER BY lflrsToActivitySetting.id ASC";
    public static final String ORDER_BY_SQL = " ORDER BY Learn_LFLRSToActivitySetting.id_ ASC";
    public static final String DATA_SOURCE = "liferayDataSource";
    public static final String SESSION_FACTORY = "liferaySessionFactory";
    public static final String TX_MANAGER = "liferayTransactionManager";
    public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.entity.cache.enabled.com.arcusys.learn.persistence.liferay.model.LFLRSToActivitySetting"),
            false);
    public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.finder.cache.enabled.com.arcusys.learn.persistence.liferay.model.LFLRSToActivitySetting"),
            false);
    public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.column.bitmask.enabled.com.arcusys.learn.persistence.liferay.model.LFLRSToActivitySetting"),
            true);
    public static long COURSEID_COLUMN_BITMASK = 1L;
    public static long ID_COLUMN_BITMASK = 2L;
    public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
                "lock.expiration.time.com.arcusys.learn.persistence.liferay.model.LFLRSToActivitySetting"));
    private static ClassLoader _classLoader = LFLRSToActivitySetting.class.getClassLoader();
    private static Class<?>[] _escapedModelInterfaces = new Class[] {
            LFLRSToActivitySetting.class
        };
    private long _id;
    private Integer _courseID;
    private Integer _originalCourseID;
    private boolean _setOriginalCourseID;
    private String _title;
    private String _activityFilter;
    private String _verbFilter;
    private long _columnBitmask;
    private LFLRSToActivitySetting _escapedModel;

    public LFLRSToActivitySettingModelImpl() {
    }

    @Override
    public long getPrimaryKey() {
        return _id;
    }

    @Override
    public void setPrimaryKey(long primaryKey) {
        setId(primaryKey);
    }

    @Override
    public Serializable getPrimaryKeyObj() {
        return _id;
    }

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj) {
        setPrimaryKey(((Long) primaryKeyObj).longValue());
    }

    @Override
    public Class<?> getModelClass() {
        return LFLRSToActivitySetting.class;
    }

    @Override
    public String getModelClassName() {
        return LFLRSToActivitySetting.class.getName();
    }

    @Override
    public Map<String, Object> getModelAttributes() {
        Map<String, Object> attributes = new HashMap<String, Object>();

        attributes.put("id", getId());
        attributes.put("courseID", getCourseID());
        attributes.put("title", getTitle());
        attributes.put("activityFilter", getActivityFilter());
        attributes.put("verbFilter", getVerbFilter());

        return attributes;
    }

    @Override
    public void setModelAttributes(Map<String, Object> attributes) {
        Long id = (Long) attributes.get("id");

        if (id != null) {
            setId(id);
        }

        Integer courseID = (Integer) attributes.get("courseID");

        if (courseID != null) {
            setCourseID(courseID);
        }

        String title = (String) attributes.get("title");

        if (title != null) {
            setTitle(title);
        }

        String activityFilter = (String) attributes.get("activityFilter");

        if (activityFilter != null) {
            setActivityFilter(activityFilter);
        }

        String verbFilter = (String) attributes.get("verbFilter");

        if (verbFilter != null) {
            setVerbFilter(verbFilter);
        }
    }

    @Override
    public long getId() {
        return _id;
    }

    @Override
    public void setId(long id) {
        _id = id;
    }

    @Override
    public Integer getCourseID() {
        return _courseID;
    }

    @Override
    public void setCourseID(Integer courseID) {
        _columnBitmask |= COURSEID_COLUMN_BITMASK;

        if (!_setOriginalCourseID) {
            _setOriginalCourseID = true;

            _originalCourseID = _courseID;
        }

        _courseID = courseID;
    }

    public Integer getOriginalCourseID() {
        return _originalCourseID;
    }

    @Override
    public String getTitle() {
        return _title;
    }

    @Override
    public void setTitle(String title) {
        _title = title;
    }

    @Override
    public String getActivityFilter() {
        return _activityFilter;
    }

    @Override
    public void setActivityFilter(String activityFilter) {
        _activityFilter = activityFilter;
    }

    @Override
    public String getVerbFilter() {
        return _verbFilter;
    }

    @Override
    public void setVerbFilter(String verbFilter) {
        _verbFilter = verbFilter;
    }

    public long getColumnBitmask() {
        return _columnBitmask;
    }

    @Override
    public ExpandoBridge getExpandoBridge() {
        return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
            LFLRSToActivitySetting.class.getName(), getPrimaryKey());
    }

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
        ExpandoBridge expandoBridge = getExpandoBridge();

        expandoBridge.setAttributes(serviceContext);
    }

    @Override
    public LFLRSToActivitySetting toEscapedModel() {
        if (_escapedModel == null) {
            _escapedModel = (LFLRSToActivitySetting) ProxyUtil.newProxyInstance(_classLoader,
                    _escapedModelInterfaces, new AutoEscapeBeanHandler(this));
        }

        return _escapedModel;
    }

    @Override
    public Object clone() {
        LFLRSToActivitySettingImpl lflrsToActivitySettingImpl = new LFLRSToActivitySettingImpl();

        lflrsToActivitySettingImpl.setId(getId());
        lflrsToActivitySettingImpl.setCourseID(getCourseID());
        lflrsToActivitySettingImpl.setTitle(getTitle());
        lflrsToActivitySettingImpl.setActivityFilter(getActivityFilter());
        lflrsToActivitySettingImpl.setVerbFilter(getVerbFilter());

        lflrsToActivitySettingImpl.resetOriginalValues();

        return lflrsToActivitySettingImpl;
    }

    @Override
    public int compareTo(LFLRSToActivitySetting lflrsToActivitySetting) {
        long primaryKey = lflrsToActivitySetting.getPrimaryKey();

        if (getPrimaryKey() < primaryKey) {
            return -1;
        } else if (getPrimaryKey() > primaryKey) {
            return 1;
        } else {
            return 0;
        }
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }

        if (!(obj instanceof LFLRSToActivitySetting)) {
            return false;
        }

        LFLRSToActivitySetting lflrsToActivitySetting = (LFLRSToActivitySetting) obj;

        long primaryKey = lflrsToActivitySetting.getPrimaryKey();

        if (getPrimaryKey() == primaryKey) {
            return true;
        } else {
            return false;
        }
    }

    @Override
    public int hashCode() {
        return (int) getPrimaryKey();
    }

    @Override
    public void resetOriginalValues() {
        LFLRSToActivitySettingModelImpl lflrsToActivitySettingModelImpl = this;

        lflrsToActivitySettingModelImpl._originalCourseID = lflrsToActivitySettingModelImpl._courseID;

        lflrsToActivitySettingModelImpl._setOriginalCourseID = false;

        lflrsToActivitySettingModelImpl._columnBitmask = 0;
    }

    @Override
    public CacheModel<LFLRSToActivitySetting> toCacheModel() {
        LFLRSToActivitySettingCacheModel lflrsToActivitySettingCacheModel = new LFLRSToActivitySettingCacheModel();

        lflrsToActivitySettingCacheModel.id = getId();

        lflrsToActivitySettingCacheModel.courseID = getCourseID();

        lflrsToActivitySettingCacheModel.title = getTitle();

        String title = lflrsToActivitySettingCacheModel.title;

        if ((title != null) && (title.length() == 0)) {
            lflrsToActivitySettingCacheModel.title = null;
        }

        lflrsToActivitySettingCacheModel.activityFilter = getActivityFilter();

        String activityFilter = lflrsToActivitySettingCacheModel.activityFilter;

        if ((activityFilter != null) && (activityFilter.length() == 0)) {
            lflrsToActivitySettingCacheModel.activityFilter = null;
        }

        lflrsToActivitySettingCacheModel.verbFilter = getVerbFilter();

        String verbFilter = lflrsToActivitySettingCacheModel.verbFilter;

        if ((verbFilter != null) && (verbFilter.length() == 0)) {
            lflrsToActivitySettingCacheModel.verbFilter = null;
        }

        return lflrsToActivitySettingCacheModel;
    }

    @Override
    public String toString() {
        StringBundler sb = new StringBundler(11);

        sb.append("{id=");
        sb.append(getId());
        sb.append(", courseID=");
        sb.append(getCourseID());
        sb.append(", title=");
        sb.append(getTitle());
        sb.append(", activityFilter=");
        sb.append(getActivityFilter());
        sb.append(", verbFilter=");
        sb.append(getVerbFilter());
        sb.append("}");

        return sb.toString();
    }

    @Override
    public String toXmlString() {
        StringBundler sb = new StringBundler(19);

        sb.append("<model><model-name>");
        sb.append(
            "com.arcusys.learn.persistence.liferay.model.LFLRSToActivitySetting");
        sb.append("</model-name>");

        sb.append(
            "<column><column-name>id</column-name><column-value><![CDATA[");
        sb.append(getId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>courseID</column-name><column-value><![CDATA[");
        sb.append(getCourseID());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>title</column-name><column-value><![CDATA[");
        sb.append(getTitle());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>activityFilter</column-name><column-value><![CDATA[");
        sb.append(getActivityFilter());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>verbFilter</column-name><column-value><![CDATA[");
        sb.append(getVerbFilter());
        sb.append("]]></column-value></column>");

        sb.append("</model>");

        return sb.toString();
    }
}
