package com.arcusys.learn.persistence.liferay.model.impl;

import com.arcusys.learn.persistence.liferay.model.LFQuizQuestCat;
import com.arcusys.learn.persistence.liferay.model.LFQuizQuestCatModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the LFQuizQuestCat service. Represents a row in the &quot;Learn_LFQuizQuestCat&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.arcusys.learn.persistence.liferay.model.LFQuizQuestCatModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LFQuizQuestCatImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LFQuizQuestCatImpl
 * @see com.arcusys.learn.persistence.liferay.model.LFQuizQuestCat
 * @see com.arcusys.learn.persistence.liferay.model.LFQuizQuestCatModel
 * @generated
 */
public class LFQuizQuestCatModelImpl extends BaseModelImpl<LFQuizQuestCat>
    implements LFQuizQuestCatModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a l f quiz quest cat model instance should use the {@link com.arcusys.learn.persistence.liferay.model.LFQuizQuestCat} interface instead.
     */
    public static final String TABLE_NAME = "Learn_LFQuizQuestCat";
    public static final Object[][] TABLE_COLUMNS = {
            { "id_", Types.BIGINT },
            { "title", Types.VARCHAR },
            { "description", Types.VARCHAR },
            { "quizId", Types.INTEGER },
            { "parentId", Types.INTEGER },
            { "arrangementIndex", Types.INTEGER }
        };
    public static final String TABLE_SQL_CREATE = "create table Learn_LFQuizQuestCat (id_ LONG not null primary key,title VARCHAR(75) null,description VARCHAR(75) null,quizId INTEGER null,parentId INTEGER null,arrangementIndex INTEGER null)";
    public static final String TABLE_SQL_DROP = "drop table Learn_LFQuizQuestCat";
    public static final String ORDER_BY_JPQL = " ORDER BY lfQuizQuestCat.id ASC";
    public static final String ORDER_BY_SQL = " ORDER BY Learn_LFQuizQuestCat.id_ ASC";
    public static final String DATA_SOURCE = "liferayDataSource";
    public static final String SESSION_FACTORY = "liferaySessionFactory";
    public static final String TX_MANAGER = "liferayTransactionManager";
    public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.entity.cache.enabled.com.arcusys.learn.persistence.liferay.model.LFQuizQuestCat"),
            false);
    public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.finder.cache.enabled.com.arcusys.learn.persistence.liferay.model.LFQuizQuestCat"),
            false);
    public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.column.bitmask.enabled.com.arcusys.learn.persistence.liferay.model.LFQuizQuestCat"),
            true);
    public static long PARENTID_COLUMN_BITMASK = 1L;
    public static long QUIZID_COLUMN_BITMASK = 2L;
    public static long ID_COLUMN_BITMASK = 4L;
    public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
                "lock.expiration.time.com.arcusys.learn.persistence.liferay.model.LFQuizQuestCat"));
    private static ClassLoader _classLoader = LFQuizQuestCat.class.getClassLoader();
    private static Class<?>[] _escapedModelInterfaces = new Class[] {
            LFQuizQuestCat.class
        };
    private long _id;
    private String _title;
    private String _description;
    private Integer _quizId;
    private Integer _originalQuizId;
    private boolean _setOriginalQuizId;
    private Integer _parentId;
    private Integer _originalParentId;
    private boolean _setOriginalParentId;
    private Integer _arrangementIndex;
    private long _columnBitmask;
    private LFQuizQuestCat _escapedModel;

    public LFQuizQuestCatModelImpl() {
    }

    @Override
    public long getPrimaryKey() {
        return _id;
    }

    @Override
    public void setPrimaryKey(long primaryKey) {
        setId(primaryKey);
    }

    @Override
    public Serializable getPrimaryKeyObj() {
        return _id;
    }

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj) {
        setPrimaryKey(((Long) primaryKeyObj).longValue());
    }

    @Override
    public Class<?> getModelClass() {
        return LFQuizQuestCat.class;
    }

    @Override
    public String getModelClassName() {
        return LFQuizQuestCat.class.getName();
    }

    @Override
    public Map<String, Object> getModelAttributes() {
        Map<String, Object> attributes = new HashMap<String, Object>();

        attributes.put("id", getId());
        attributes.put("title", getTitle());
        attributes.put("description", getDescription());
        attributes.put("quizId", getQuizId());
        attributes.put("parentId", getParentId());
        attributes.put("arrangementIndex", getArrangementIndex());

        return attributes;
    }

    @Override
    public void setModelAttributes(Map<String, Object> attributes) {
        Long id = (Long) attributes.get("id");

        if (id != null) {
            setId(id);
        }

        String title = (String) attributes.get("title");

        if (title != null) {
            setTitle(title);
        }

        String description = (String) attributes.get("description");

        if (description != null) {
            setDescription(description);
        }

        Integer quizId = (Integer) attributes.get("quizId");

        if (quizId != null) {
            setQuizId(quizId);
        }

        Integer parentId = (Integer) attributes.get("parentId");

        if (parentId != null) {
            setParentId(parentId);
        }

        Integer arrangementIndex = (Integer) attributes.get("arrangementIndex");

        if (arrangementIndex != null) {
            setArrangementIndex(arrangementIndex);
        }
    }

    @Override
    public long getId() {
        return _id;
    }

    @Override
    public void setId(long id) {
        _id = id;
    }

    @Override
    public String getTitle() {
        if (_title == null) {
            return StringPool.BLANK;
        } else {
            return _title;
        }
    }

    @Override
    public void setTitle(String title) {
        _title = title;
    }

    @Override
    public String getDescription() {
        if (_description == null) {
            return StringPool.BLANK;
        } else {
            return _description;
        }
    }

    @Override
    public void setDescription(String description) {
        _description = description;
    }

    @Override
    public Integer getQuizId() {
        return _quizId;
    }

    @Override
    public void setQuizId(Integer quizId) {
        _columnBitmask |= QUIZID_COLUMN_BITMASK;

        if (!_setOriginalQuizId) {
            _setOriginalQuizId = true;

            _originalQuizId = _quizId;
        }

        _quizId = quizId;
    }

    public Integer getOriginalQuizId() {
        return _originalQuizId;
    }

    @Override
    public Integer getParentId() {
        return _parentId;
    }

    @Override
    public void setParentId(Integer parentId) {
        _columnBitmask |= PARENTID_COLUMN_BITMASK;

        if (!_setOriginalParentId) {
            _setOriginalParentId = true;

            _originalParentId = _parentId;
        }

        _parentId = parentId;
    }

    public Integer getOriginalParentId() {
        return _originalParentId;
    }

    @Override
    public Integer getArrangementIndex() {
        return _arrangementIndex;
    }

    @Override
    public void setArrangementIndex(Integer arrangementIndex) {
        _arrangementIndex = arrangementIndex;
    }

    public long getColumnBitmask() {
        return _columnBitmask;
    }

    @Override
    public ExpandoBridge getExpandoBridge() {
        return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
            LFQuizQuestCat.class.getName(), getPrimaryKey());
    }

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
        ExpandoBridge expandoBridge = getExpandoBridge();

        expandoBridge.setAttributes(serviceContext);
    }

    @Override
    public LFQuizQuestCat toEscapedModel() {
        if (_escapedModel == null) {
            _escapedModel = (LFQuizQuestCat) ProxyUtil.newProxyInstance(_classLoader,
                    _escapedModelInterfaces, new AutoEscapeBeanHandler(this));
        }

        return _escapedModel;
    }

    @Override
    public Object clone() {
        LFQuizQuestCatImpl lfQuizQuestCatImpl = new LFQuizQuestCatImpl();

        lfQuizQuestCatImpl.setId(getId());
        lfQuizQuestCatImpl.setTitle(getTitle());
        lfQuizQuestCatImpl.setDescription(getDescription());
        lfQuizQuestCatImpl.setQuizId(getQuizId());
        lfQuizQuestCatImpl.setParentId(getParentId());
        lfQuizQuestCatImpl.setArrangementIndex(getArrangementIndex());

        lfQuizQuestCatImpl.resetOriginalValues();

        return lfQuizQuestCatImpl;
    }

    @Override
    public int compareTo(LFQuizQuestCat lfQuizQuestCat) {
        long primaryKey = lfQuizQuestCat.getPrimaryKey();

        if (getPrimaryKey() < primaryKey) {
            return -1;
        } else if (getPrimaryKey() > primaryKey) {
            return 1;
        } else {
            return 0;
        }
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }

        if (!(obj instanceof LFQuizQuestCat)) {
            return false;
        }

        LFQuizQuestCat lfQuizQuestCat = (LFQuizQuestCat) obj;

        long primaryKey = lfQuizQuestCat.getPrimaryKey();

        if (getPrimaryKey() == primaryKey) {
            return true;
        } else {
            return false;
        }
    }

    @Override
    public int hashCode() {
        return (int) getPrimaryKey();
    }

    @Override
    public void resetOriginalValues() {
        LFQuizQuestCatModelImpl lfQuizQuestCatModelImpl = this;

        lfQuizQuestCatModelImpl._originalQuizId = lfQuizQuestCatModelImpl._quizId;

        lfQuizQuestCatModelImpl._setOriginalQuizId = false;

        lfQuizQuestCatModelImpl._originalParentId = lfQuizQuestCatModelImpl._parentId;

        lfQuizQuestCatModelImpl._setOriginalParentId = false;

        lfQuizQuestCatModelImpl._columnBitmask = 0;
    }

    @Override
    public CacheModel<LFQuizQuestCat> toCacheModel() {
        LFQuizQuestCatCacheModel lfQuizQuestCatCacheModel = new LFQuizQuestCatCacheModel();

        lfQuizQuestCatCacheModel.id = getId();

        lfQuizQuestCatCacheModel.title = getTitle();

        String title = lfQuizQuestCatCacheModel.title;

        if ((title != null) && (title.length() == 0)) {
            lfQuizQuestCatCacheModel.title = null;
        }

        lfQuizQuestCatCacheModel.description = getDescription();

        String description = lfQuizQuestCatCacheModel.description;

        if ((description != null) && (description.length() == 0)) {
            lfQuizQuestCatCacheModel.description = null;
        }

        lfQuizQuestCatCacheModel.quizId = getQuizId();

        lfQuizQuestCatCacheModel.parentId = getParentId();

        lfQuizQuestCatCacheModel.arrangementIndex = getArrangementIndex();

        return lfQuizQuestCatCacheModel;
    }

    @Override
    public String toString() {
        StringBundler sb = new StringBundler(13);

        sb.append("{id=");
        sb.append(getId());
        sb.append(", title=");
        sb.append(getTitle());
        sb.append(", description=");
        sb.append(getDescription());
        sb.append(", quizId=");
        sb.append(getQuizId());
        sb.append(", parentId=");
        sb.append(getParentId());
        sb.append(", arrangementIndex=");
        sb.append(getArrangementIndex());
        sb.append("}");

        return sb.toString();
    }

    @Override
    public String toXmlString() {
        StringBundler sb = new StringBundler(22);

        sb.append("<model><model-name>");
        sb.append("com.arcusys.learn.persistence.liferay.model.LFQuizQuestCat");
        sb.append("</model-name>");

        sb.append(
            "<column><column-name>id</column-name><column-value><![CDATA[");
        sb.append(getId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>title</column-name><column-value><![CDATA[");
        sb.append(getTitle());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>description</column-name><column-value><![CDATA[");
        sb.append(getDescription());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>quizId</column-name><column-value><![CDATA[");
        sb.append(getQuizId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>parentId</column-name><column-value><![CDATA[");
        sb.append(getParentId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>arrangementIndex</column-name><column-value><![CDATA[");
        sb.append(getArrangementIndex());
        sb.append("]]></column-value></column>");

        sb.append("</model>");

        return sb.toString();
    }
}
