package com.arcusys.learn.persistence.liferay.model.impl;

import com.arcusys.learn.persistence.liferay.model.LFQuizQuestCat;
import com.arcusys.learn.persistence.liferay.service.LFQuizQuestCatLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the LFQuizQuestCat service. Represents a row in the &quot;Learn_LFQuizQuestCat&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LFQuizQuestCatImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LFQuizQuestCatImpl
 * @see com.arcusys.learn.persistence.liferay.model.LFQuizQuestCat
 * @generated
 */
public abstract class LFQuizQuestCatBaseImpl extends LFQuizQuestCatModelImpl
    implements LFQuizQuestCat {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a l f quiz quest cat model instance should use the {@link LFQuizQuestCat} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            LFQuizQuestCatLocalServiceUtil.addLFQuizQuestCat(this);
        } else {
            LFQuizQuestCatLocalServiceUtil.updateLFQuizQuestCat(this);
        }
    }
}
