package com.arcusys.learn.persistence.liferay.model.impl;

import com.arcusys.learn.persistence.liferay.model.LFTincanActor;
import com.arcusys.learn.persistence.liferay.service.LFTincanActorLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the LFTincanActor service. Represents a row in the &quot;Learn_LFTincanActor&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LFTincanActorImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LFTincanActorImpl
 * @see com.arcusys.learn.persistence.liferay.model.LFTincanActor
 * @generated
 */
public abstract class LFTincanActorBaseImpl extends LFTincanActorModelImpl
    implements LFTincanActor {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a l f tincan actor model instance should use the {@link LFTincanActor} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            LFTincanActorLocalServiceUtil.addLFTincanActor(this);
        } else {
            LFTincanActorLocalServiceUtil.updateLFTincanActor(this);
        }
    }
}
