package com.arcusys.learn.persistence.liferay.model.impl;

import com.arcusys.learn.persistence.liferay.model.LFTincanManifestAct;
import com.arcusys.learn.persistence.liferay.service.LFTincanManifestActLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the LFTincanManifestAct service. Represents a row in the &quot;Learn_LFTincanManifestAct&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LFTincanManifestActImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LFTincanManifestActImpl
 * @see com.arcusys.learn.persistence.liferay.model.LFTincanManifestAct
 * @generated
 */
public abstract class LFTincanManifestActBaseImpl
    extends LFTincanManifestActModelImpl implements LFTincanManifestAct {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a l f tincan manifest act model instance should use the {@link LFTincanManifestAct} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            LFTincanManifestActLocalServiceUtil.addLFTincanManifestAct(this);
        } else {
            LFTincanManifestActLocalServiceUtil.updateLFTincanManifestAct(this);
        }
    }
}
