package com.arcusys.learn.persistence.liferay.model.impl;

import com.arcusys.learn.persistence.liferay.model.LFTincanCtxActivities;
import com.arcusys.learn.persistence.liferay.model.LFTincanCtxActivitiesModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the LFTincanCtxActivities service. Represents a row in the &quot;Learn_LFTincanCtxActivities&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.arcusys.learn.persistence.liferay.model.LFTincanCtxActivitiesModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LFTincanCtxActivitiesImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LFTincanCtxActivitiesImpl
 * @see com.arcusys.learn.persistence.liferay.model.LFTincanCtxActivities
 * @see com.arcusys.learn.persistence.liferay.model.LFTincanCtxActivitiesModel
 * @generated
 */
public class LFTincanCtxActivitiesModelImpl extends BaseModelImpl<LFTincanCtxActivities>
    implements LFTincanCtxActivitiesModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a l f tincan ctx activities model instance should use the {@link com.arcusys.learn.persistence.liferay.model.LFTincanCtxActivities} interface instead.
     */
    public static final String TABLE_NAME = "Learn_LFTincanCtxActivities";
    public static final Object[][] TABLE_COLUMNS = {
            { "id_", Types.BIGINT },
            { "parent", Types.VARCHAR },
            { "grouping", Types.VARCHAR },
            { "category", Types.VARCHAR },
            { "other", Types.VARCHAR }
        };
    public static final String TABLE_SQL_CREATE = "create table Learn_LFTincanCtxActivities (id_ LONG not null primary key,parent VARCHAR(3000) null,grouping VARCHAR(3000) null,category VARCHAR(3000) null,other VARCHAR(3000) null)";
    public static final String TABLE_SQL_DROP = "drop table Learn_LFTincanCtxActivities";
    public static final String ORDER_BY_JPQL = " ORDER BY lfTincanCtxActivities.id ASC";
    public static final String ORDER_BY_SQL = " ORDER BY Learn_LFTincanCtxActivities.id_ ASC";
    public static final String DATA_SOURCE = "liferayDataSource";
    public static final String SESSION_FACTORY = "liferaySessionFactory";
    public static final String TX_MANAGER = "liferayTransactionManager";
    public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.entity.cache.enabled.com.arcusys.learn.persistence.liferay.model.LFTincanCtxActivities"),
            false);
    public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.finder.cache.enabled.com.arcusys.learn.persistence.liferay.model.LFTincanCtxActivities"),
            false);
    public static final boolean COLUMN_BITMASK_ENABLED = false;
    public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
                "lock.expiration.time.com.arcusys.learn.persistence.liferay.model.LFTincanCtxActivities"));
    private static ClassLoader _classLoader = LFTincanCtxActivities.class.getClassLoader();
    private static Class<?>[] _escapedModelInterfaces = new Class[] {
            LFTincanCtxActivities.class
        };
    private long _id;
    private String _parent;
    private String _grouping;
    private String _category;
    private String _other;
    private LFTincanCtxActivities _escapedModel;

    public LFTincanCtxActivitiesModelImpl() {
    }

    @Override
    public long getPrimaryKey() {
        return _id;
    }

    @Override
    public void setPrimaryKey(long primaryKey) {
        setId(primaryKey);
    }

    @Override
    public Serializable getPrimaryKeyObj() {
        return _id;
    }

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj) {
        setPrimaryKey(((Long) primaryKeyObj).longValue());
    }

    @Override
    public Class<?> getModelClass() {
        return LFTincanCtxActivities.class;
    }

    @Override
    public String getModelClassName() {
        return LFTincanCtxActivities.class.getName();
    }

    @Override
    public Map<String, Object> getModelAttributes() {
        Map<String, Object> attributes = new HashMap<String, Object>();

        attributes.put("id", getId());
        attributes.put("parent", getParent());
        attributes.put("grouping", getGrouping());
        attributes.put("category", getCategory());
        attributes.put("other", getOther());

        return attributes;
    }

    @Override
    public void setModelAttributes(Map<String, Object> attributes) {
        Long id = (Long) attributes.get("id");

        if (id != null) {
            setId(id);
        }

        String parent = (String) attributes.get("parent");

        if (parent != null) {
            setParent(parent);
        }

        String grouping = (String) attributes.get("grouping");

        if (grouping != null) {
            setGrouping(grouping);
        }

        String category = (String) attributes.get("category");

        if (category != null) {
            setCategory(category);
        }

        String other = (String) attributes.get("other");

        if (other != null) {
            setOther(other);
        }
    }

    @Override
    public long getId() {
        return _id;
    }

    @Override
    public void setId(long id) {
        _id = id;
    }

    @Override
    public String getParent() {
        return _parent;
    }

    @Override
    public void setParent(String parent) {
        _parent = parent;
    }

    @Override
    public String getGrouping() {
        return _grouping;
    }

    @Override
    public void setGrouping(String grouping) {
        _grouping = grouping;
    }

    @Override
    public String getCategory() {
        return _category;
    }

    @Override
    public void setCategory(String category) {
        _category = category;
    }

    @Override
    public String getOther() {
        return _other;
    }

    @Override
    public void setOther(String other) {
        _other = other;
    }

    @Override
    public ExpandoBridge getExpandoBridge() {
        return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
            LFTincanCtxActivities.class.getName(), getPrimaryKey());
    }

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
        ExpandoBridge expandoBridge = getExpandoBridge();

        expandoBridge.setAttributes(serviceContext);
    }

    @Override
    public LFTincanCtxActivities toEscapedModel() {
        if (_escapedModel == null) {
            _escapedModel = (LFTincanCtxActivities) ProxyUtil.newProxyInstance(_classLoader,
                    _escapedModelInterfaces, new AutoEscapeBeanHandler(this));
        }

        return _escapedModel;
    }

    @Override
    public Object clone() {
        LFTincanCtxActivitiesImpl lfTincanCtxActivitiesImpl = new LFTincanCtxActivitiesImpl();

        lfTincanCtxActivitiesImpl.setId(getId());
        lfTincanCtxActivitiesImpl.setParent(getParent());
        lfTincanCtxActivitiesImpl.setGrouping(getGrouping());
        lfTincanCtxActivitiesImpl.setCategory(getCategory());
        lfTincanCtxActivitiesImpl.setOther(getOther());

        lfTincanCtxActivitiesImpl.resetOriginalValues();

        return lfTincanCtxActivitiesImpl;
    }

    @Override
    public int compareTo(LFTincanCtxActivities lfTincanCtxActivities) {
        long primaryKey = lfTincanCtxActivities.getPrimaryKey();

        if (getPrimaryKey() < primaryKey) {
            return -1;
        } else if (getPrimaryKey() > primaryKey) {
            return 1;
        } else {
            return 0;
        }
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }

        if (!(obj instanceof LFTincanCtxActivities)) {
            return false;
        }

        LFTincanCtxActivities lfTincanCtxActivities = (LFTincanCtxActivities) obj;

        long primaryKey = lfTincanCtxActivities.getPrimaryKey();

        if (getPrimaryKey() == primaryKey) {
            return true;
        } else {
            return false;
        }
    }

    @Override
    public int hashCode() {
        return (int) getPrimaryKey();
    }

    @Override
    public void resetOriginalValues() {
    }

    @Override
    public CacheModel<LFTincanCtxActivities> toCacheModel() {
        LFTincanCtxActivitiesCacheModel lfTincanCtxActivitiesCacheModel = new LFTincanCtxActivitiesCacheModel();

        lfTincanCtxActivitiesCacheModel.id = getId();

        lfTincanCtxActivitiesCacheModel.parent = getParent();

        String parent = lfTincanCtxActivitiesCacheModel.parent;

        if ((parent != null) && (parent.length() == 0)) {
            lfTincanCtxActivitiesCacheModel.parent = null;
        }

        lfTincanCtxActivitiesCacheModel.grouping = getGrouping();

        String grouping = lfTincanCtxActivitiesCacheModel.grouping;

        if ((grouping != null) && (grouping.length() == 0)) {
            lfTincanCtxActivitiesCacheModel.grouping = null;
        }

        lfTincanCtxActivitiesCacheModel.category = getCategory();

        String category = lfTincanCtxActivitiesCacheModel.category;

        if ((category != null) && (category.length() == 0)) {
            lfTincanCtxActivitiesCacheModel.category = null;
        }

        lfTincanCtxActivitiesCacheModel.other = getOther();

        String other = lfTincanCtxActivitiesCacheModel.other;

        if ((other != null) && (other.length() == 0)) {
            lfTincanCtxActivitiesCacheModel.other = null;
        }

        return lfTincanCtxActivitiesCacheModel;
    }

    @Override
    public String toString() {
        StringBundler sb = new StringBundler(11);

        sb.append("{id=");
        sb.append(getId());
        sb.append(", parent=");
        sb.append(getParent());
        sb.append(", grouping=");
        sb.append(getGrouping());
        sb.append(", category=");
        sb.append(getCategory());
        sb.append(", other=");
        sb.append(getOther());
        sb.append("}");

        return sb.toString();
    }

    @Override
    public String toXmlString() {
        StringBundler sb = new StringBundler(19);

        sb.append("<model><model-name>");
        sb.append(
            "com.arcusys.learn.persistence.liferay.model.LFTincanCtxActivities");
        sb.append("</model-name>");

        sb.append(
            "<column><column-name>id</column-name><column-value><![CDATA[");
        sb.append(getId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>parent</column-name><column-value><![CDATA[");
        sb.append(getParent());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>grouping</column-name><column-value><![CDATA[");
        sb.append(getGrouping());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>category</column-name><column-value><![CDATA[");
        sb.append(getCategory());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>other</column-name><column-value><![CDATA[");
        sb.append(getOther());
        sb.append("]]></column-value></column>");

        sb.append("</model>");

        return sb.toString();
    }
}
