package com.arcusys.learn.persistence.liferay.model.impl;

import com.arcusys.learn.persistence.liferay.model.LFTincanClientApiStorage;
import com.arcusys.learn.persistence.liferay.service.LFTincanClientApiStorageLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the LFTincanClientApiStorage service. Represents a row in the &quot;Learn_LFTincanClientApiStorage&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LFTincanClientApiStorageImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LFTincanClientApiStorageImpl
 * @see com.arcusys.learn.persistence.liferay.model.LFTincanClientApiStorage
 * @generated
 */
public abstract class LFTincanClientApiStorageBaseImpl
    extends LFTincanClientApiStorageModelImpl
    implements LFTincanClientApiStorage {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a l f tincan client api storage model instance should use the {@link LFTincanClientApiStorage} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            LFTincanClientApiStorageLocalServiceUtil.addLFTincanClientApiStorage(this);
        } else {
            LFTincanClientApiStorageLocalServiceUtil.updateLFTincanClientApiStorage(this);
        }
    }
}
