package com.arcusys.learn.persistence.liferay.model.impl;

import com.arcusys.learn.persistence.liferay.model.LFActivityDataMap;
import com.arcusys.learn.persistence.liferay.service.LFActivityDataMapLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the LFActivityDataMap service. Represents a row in the &quot;Learn_LFActivityDataMap&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LFActivityDataMapImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LFActivityDataMapImpl
 * @see com.arcusys.learn.persistence.liferay.model.LFActivityDataMap
 * @generated
 */
public abstract class LFActivityDataMapBaseImpl
    extends LFActivityDataMapModelImpl implements LFActivityDataMap {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a l f activity data map model instance should use the {@link LFActivityDataMap} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            LFActivityDataMapLocalServiceUtil.addLFActivityDataMap(this);
        } else {
            LFActivityDataMapLocalServiceUtil.updateLFActivityDataMap(this);
        }
    }
}
