package com.arcusys.learn.persistence.liferay.model.impl;

import com.arcusys.learn.persistence.liferay.model.LFActivityState;
import com.arcusys.learn.persistence.liferay.service.LFActivityStateLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the LFActivityState service. Represents a row in the &quot;Learn_LFActivityState&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LFActivityStateImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LFActivityStateImpl
 * @see com.arcusys.learn.persistence.liferay.model.LFActivityState
 * @generated
 */
public abstract class LFActivityStateBaseImpl extends LFActivityStateModelImpl
    implements LFActivityState {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a l f activity state model instance should use the {@link LFActivityState} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            LFActivityStateLocalServiceUtil.addLFActivityState(this);
        } else {
            LFActivityStateLocalServiceUtil.updateLFActivityState(this);
        }
    }
}
