package com.arcusys.learn.persistence.liferay.model.impl;

import com.arcusys.learn.persistence.liferay.model.LFAchievementUser;
import com.arcusys.learn.persistence.liferay.model.LFAchievementUserModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the LFAchievementUser service. Represents a row in the &quot;Learn_LFAchievementUser&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.arcusys.learn.persistence.liferay.model.LFAchievementUserModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LFAchievementUserImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LFAchievementUserImpl
 * @see com.arcusys.learn.persistence.liferay.model.LFAchievementUser
 * @see com.arcusys.learn.persistence.liferay.model.LFAchievementUserModel
 * @generated
 */
public class LFAchievementUserModelImpl extends BaseModelImpl<LFAchievementUser>
    implements LFAchievementUserModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a l f achievement user model instance should use the {@link com.arcusys.learn.persistence.liferay.model.LFAchievementUser} interface instead.
     */
    public static final String TABLE_NAME = "Learn_LFAchievementUser";
    public static final Object[][] TABLE_COLUMNS = {
            { "id_", Types.BIGINT },
            { "userId", Types.INTEGER },
            { "achievementId", Types.INTEGER }
        };
    public static final String TABLE_SQL_CREATE = "create table Learn_LFAchievementUser (id_ LONG not null primary key,userId INTEGER null,achievementId INTEGER null)";
    public static final String TABLE_SQL_DROP = "drop table Learn_LFAchievementUser";
    public static final String ORDER_BY_JPQL = " ORDER BY lfAchievementUser.id ASC";
    public static final String ORDER_BY_SQL = " ORDER BY Learn_LFAchievementUser.id_ ASC";
    public static final String DATA_SOURCE = "liferayDataSource";
    public static final String SESSION_FACTORY = "liferaySessionFactory";
    public static final String TX_MANAGER = "liferayTransactionManager";
    public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.entity.cache.enabled.com.arcusys.learn.persistence.liferay.model.LFAchievementUser"),
            false);
    public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.finder.cache.enabled.com.arcusys.learn.persistence.liferay.model.LFAchievementUser"),
            false);
    public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.column.bitmask.enabled.com.arcusys.learn.persistence.liferay.model.LFAchievementUser"),
            true);
    public static long ACHIEVEMENTID_COLUMN_BITMASK = 1L;
    public static long USERID_COLUMN_BITMASK = 2L;
    public static long ID_COLUMN_BITMASK = 4L;
    public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
                "lock.expiration.time.com.arcusys.learn.persistence.liferay.model.LFAchievementUser"));
    private static ClassLoader _classLoader = LFAchievementUser.class.getClassLoader();
    private static Class<?>[] _escapedModelInterfaces = new Class[] {
            LFAchievementUser.class
        };
    private long _id;
    private Integer _userId;
    private Integer _originalUserId;
    private boolean _setOriginalUserId;
    private Integer _achievementId;
    private Integer _originalAchievementId;
    private boolean _setOriginalAchievementId;
    private long _columnBitmask;
    private LFAchievementUser _escapedModel;

    public LFAchievementUserModelImpl() {
    }

    @Override
    public long getPrimaryKey() {
        return _id;
    }

    @Override
    public void setPrimaryKey(long primaryKey) {
        setId(primaryKey);
    }

    @Override
    public Serializable getPrimaryKeyObj() {
        return _id;
    }

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj) {
        setPrimaryKey(((Long) primaryKeyObj).longValue());
    }

    @Override
    public Class<?> getModelClass() {
        return LFAchievementUser.class;
    }

    @Override
    public String getModelClassName() {
        return LFAchievementUser.class.getName();
    }

    @Override
    public Map<String, Object> getModelAttributes() {
        Map<String, Object> attributes = new HashMap<String, Object>();

        attributes.put("id", getId());
        attributes.put("userId", getUserId());
        attributes.put("achievementId", getAchievementId());

        return attributes;
    }

    @Override
    public void setModelAttributes(Map<String, Object> attributes) {
        Long id = (Long) attributes.get("id");

        if (id != null) {
            setId(id);
        }

        Integer userId = (Integer) attributes.get("userId");

        if (userId != null) {
            setUserId(userId);
        }

        Integer achievementId = (Integer) attributes.get("achievementId");

        if (achievementId != null) {
            setAchievementId(achievementId);
        }
    }

    @Override
    public long getId() {
        return _id;
    }

    @Override
    public void setId(long id) {
        _id = id;
    }

    @Override
    public Integer getUserId() {
        return _userId;
    }

    @Override
    public void setUserId(Integer userId) {
        _columnBitmask |= USERID_COLUMN_BITMASK;

        if (!_setOriginalUserId) {
            _setOriginalUserId = true;

            _originalUserId = _userId;
        }

        _userId = userId;
    }

    public Integer getOriginalUserId() {
        return _originalUserId;
    }

    @Override
    public Integer getAchievementId() {
        return _achievementId;
    }

    @Override
    public void setAchievementId(Integer achievementId) {
        _columnBitmask |= ACHIEVEMENTID_COLUMN_BITMASK;

        if (!_setOriginalAchievementId) {
            _setOriginalAchievementId = true;

            _originalAchievementId = _achievementId;
        }

        _achievementId = achievementId;
    }

    public Integer getOriginalAchievementId() {
        return _originalAchievementId;
    }

    public long getColumnBitmask() {
        return _columnBitmask;
    }

    @Override
    public ExpandoBridge getExpandoBridge() {
        return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
            LFAchievementUser.class.getName(), getPrimaryKey());
    }

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
        ExpandoBridge expandoBridge = getExpandoBridge();

        expandoBridge.setAttributes(serviceContext);
    }

    @Override
    public LFAchievementUser toEscapedModel() {
        if (_escapedModel == null) {
            _escapedModel = (LFAchievementUser) ProxyUtil.newProxyInstance(_classLoader,
                    _escapedModelInterfaces, new AutoEscapeBeanHandler(this));
        }

        return _escapedModel;
    }

    @Override
    public Object clone() {
        LFAchievementUserImpl lfAchievementUserImpl = new LFAchievementUserImpl();

        lfAchievementUserImpl.setId(getId());
        lfAchievementUserImpl.setUserId(getUserId());
        lfAchievementUserImpl.setAchievementId(getAchievementId());

        lfAchievementUserImpl.resetOriginalValues();

        return lfAchievementUserImpl;
    }

    @Override
    public int compareTo(LFAchievementUser lfAchievementUser) {
        long primaryKey = lfAchievementUser.getPrimaryKey();

        if (getPrimaryKey() < primaryKey) {
            return -1;
        } else if (getPrimaryKey() > primaryKey) {
            return 1;
        } else {
            return 0;
        }
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }

        if (!(obj instanceof LFAchievementUser)) {
            return false;
        }

        LFAchievementUser lfAchievementUser = (LFAchievementUser) obj;

        long primaryKey = lfAchievementUser.getPrimaryKey();

        if (getPrimaryKey() == primaryKey) {
            return true;
        } else {
            return false;
        }
    }

    @Override
    public int hashCode() {
        return (int) getPrimaryKey();
    }

    @Override
    public void resetOriginalValues() {
        LFAchievementUserModelImpl lfAchievementUserModelImpl = this;

        lfAchievementUserModelImpl._originalUserId = lfAchievementUserModelImpl._userId;

        lfAchievementUserModelImpl._setOriginalUserId = false;

        lfAchievementUserModelImpl._originalAchievementId = lfAchievementUserModelImpl._achievementId;

        lfAchievementUserModelImpl._setOriginalAchievementId = false;

        lfAchievementUserModelImpl._columnBitmask = 0;
    }

    @Override
    public CacheModel<LFAchievementUser> toCacheModel() {
        LFAchievementUserCacheModel lfAchievementUserCacheModel = new LFAchievementUserCacheModel();

        lfAchievementUserCacheModel.id = getId();

        lfAchievementUserCacheModel.userId = getUserId();

        lfAchievementUserCacheModel.achievementId = getAchievementId();

        return lfAchievementUserCacheModel;
    }

    @Override
    public String toString() {
        StringBundler sb = new StringBundler(7);

        sb.append("{id=");
        sb.append(getId());
        sb.append(", userId=");
        sb.append(getUserId());
        sb.append(", achievementId=");
        sb.append(getAchievementId());
        sb.append("}");

        return sb.toString();
    }

    @Override
    public String toXmlString() {
        StringBundler sb = new StringBundler(13);

        sb.append("<model><model-name>");
        sb.append(
            "com.arcusys.learn.persistence.liferay.model.LFAchievementUser");
        sb.append("</model-name>");

        sb.append(
            "<column><column-name>id</column-name><column-value><![CDATA[");
        sb.append(getId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>userId</column-name><column-value><![CDATA[");
        sb.append(getUserId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>achievementId</column-name><column-value><![CDATA[");
        sb.append(getAchievementId());
        sb.append("]]></column-value></column>");

        sb.append("</model>");

        return sb.toString();
    }
}
