package com.arcusys.learn.persistence.liferay.model.impl;

import com.arcusys.learn.persistence.liferay.model.LFCertificateSite;
import com.arcusys.learn.persistence.liferay.service.LFCertificateSiteLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the LFCertificateSite service. Represents a row in the &quot;Learn_LFCertificateSite&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LFCertificateSiteImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LFCertificateSiteImpl
 * @see com.arcusys.learn.persistence.liferay.model.LFCertificateSite
 * @generated
 */
public abstract class LFCertificateSiteBaseImpl
    extends LFCertificateSiteModelImpl implements LFCertificateSite {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a l f certificate site model instance should use the {@link LFCertificateSite} interface instead.
     */
    public void persist() throws SystemException {
        if (this.isNew()) {
            LFCertificateSiteLocalServiceUtil.addLFCertificateSite(this);
        } else {
            LFCertificateSiteLocalServiceUtil.updateLFCertificateSite(this);
        }
    }
}
