package com.arcusys.learn.persistence.liferay.model.impl;

import com.arcusys.learn.persistence.liferay.model.LFQuiz;
import com.arcusys.learn.persistence.liferay.service.LFQuizLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the LFQuiz service. Represents a row in the &quot;Learn_LFQuiz&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LFQuizImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LFQuizImpl
 * @see com.arcusys.learn.persistence.liferay.model.LFQuiz
 * @generated
 */
public abstract class LFQuizBaseImpl extends LFQuizModelImpl implements LFQuiz {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a l f quiz model instance should use the {@link LFQuiz} interface instead.
     */
    public void persist() throws SystemException {
        if (this.isNew()) {
            LFQuizLocalServiceUtil.addLFQuiz(this);
        } else {
            LFQuizLocalServiceUtil.updateLFQuiz(this);
        }
    }
}
