package com.arcusys.learn.persistence.liferay.model.impl;

import com.arcusys.learn.persistence.liferay.model.LFSocialPackageTag;
import com.arcusys.learn.persistence.liferay.model.LFSocialPackageTagModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the LFSocialPackageTag service. Represents a row in the &quot;Learn_LFSocialPackageTag&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.arcusys.learn.persistence.liferay.model.LFSocialPackageTagModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LFSocialPackageTagImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LFSocialPackageTagImpl
 * @see com.arcusys.learn.persistence.liferay.model.LFSocialPackageTag
 * @see com.arcusys.learn.persistence.liferay.model.LFSocialPackageTagModel
 * @generated
 */
public class LFSocialPackageTagModelImpl extends BaseModelImpl<LFSocialPackageTag>
    implements LFSocialPackageTagModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a l f social package tag model instance should use the {@link com.arcusys.learn.persistence.liferay.model.LFSocialPackageTag} interface instead.
     */
    public static final String TABLE_NAME = "Learn_LFSocialPackageTag";
    public static final Object[][] TABLE_COLUMNS = {
            { "id_", Types.BIGINT },
            { "socialPackageID", Types.INTEGER },
            { "name", Types.VARCHAR }
        };
    public static final String TABLE_SQL_CREATE = "create table Learn_LFSocialPackageTag (id_ LONG not null primary key,socialPackageID INTEGER null,name VARCHAR(75) null)";
    public static final String TABLE_SQL_DROP = "drop table Learn_LFSocialPackageTag";
    public static final String ORDER_BY_JPQL = " ORDER BY lfSocialPackageTag.id ASC";
    public static final String ORDER_BY_SQL = " ORDER BY Learn_LFSocialPackageTag.id_ ASC";
    public static final String DATA_SOURCE = "liferayDataSource";
    public static final String SESSION_FACTORY = "liferaySessionFactory";
    public static final String TX_MANAGER = "liferayTransactionManager";
    public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.entity.cache.enabled.com.arcusys.learn.persistence.liferay.model.LFSocialPackageTag"),
            false);
    public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.finder.cache.enabled.com.arcusys.learn.persistence.liferay.model.LFSocialPackageTag"),
            false);
    public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.column.bitmask.enabled.com.arcusys.learn.persistence.liferay.model.LFSocialPackageTag"),
            true);
    public static long NAME_COLUMN_BITMASK = 1L;
    public static long SOCIALPACKAGEID_COLUMN_BITMASK = 2L;
    public static long ID_COLUMN_BITMASK = 4L;
    public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
                "lock.expiration.time.com.arcusys.learn.persistence.liferay.model.LFSocialPackageTag"));
    private static ClassLoader _classLoader = LFSocialPackageTag.class.getClassLoader();
    private static Class<?>[] _escapedModelInterfaces = new Class[] {
            LFSocialPackageTag.class
        };
    private long _id;
    private Integer _socialPackageID;
    private Integer _originalSocialPackageID;
    private boolean _setOriginalSocialPackageID;
    private String _name;
    private String _originalName;
    private long _columnBitmask;
    private LFSocialPackageTag _escapedModel;

    public LFSocialPackageTagModelImpl() {
    }

    @Override
    public long getPrimaryKey() {
        return _id;
    }

    @Override
    public void setPrimaryKey(long primaryKey) {
        setId(primaryKey);
    }

    @Override
    public Serializable getPrimaryKeyObj() {
        return _id;
    }

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj) {
        setPrimaryKey(((Long) primaryKeyObj).longValue());
    }

    @Override
    public Class<?> getModelClass() {
        return LFSocialPackageTag.class;
    }

    @Override
    public String getModelClassName() {
        return LFSocialPackageTag.class.getName();
    }

    @Override
    public Map<String, Object> getModelAttributes() {
        Map<String, Object> attributes = new HashMap<String, Object>();

        attributes.put("id", getId());
        attributes.put("socialPackageID", getSocialPackageID());
        attributes.put("name", getName());

        return attributes;
    }

    @Override
    public void setModelAttributes(Map<String, Object> attributes) {
        Long id = (Long) attributes.get("id");

        if (id != null) {
            setId(id);
        }

        Integer socialPackageID = (Integer) attributes.get("socialPackageID");

        if (socialPackageID != null) {
            setSocialPackageID(socialPackageID);
        }

        String name = (String) attributes.get("name");

        if (name != null) {
            setName(name);
        }
    }

    @Override
    public long getId() {
        return _id;
    }

    @Override
    public void setId(long id) {
        _id = id;
    }

    @Override
    public Integer getSocialPackageID() {
        return _socialPackageID;
    }

    @Override
    public void setSocialPackageID(Integer socialPackageID) {
        _columnBitmask |= SOCIALPACKAGEID_COLUMN_BITMASK;

        if (!_setOriginalSocialPackageID) {
            _setOriginalSocialPackageID = true;

            _originalSocialPackageID = _socialPackageID;
        }

        _socialPackageID = socialPackageID;
    }

    public Integer getOriginalSocialPackageID() {
        return _originalSocialPackageID;
    }

    @Override
    public String getName() {
        return _name;
    }

    @Override
    public void setName(String name) {
        _columnBitmask |= NAME_COLUMN_BITMASK;

        if (_originalName == null) {
            _originalName = _name;
        }

        _name = name;
    }

    public String getOriginalName() {
        return _originalName;
    }

    public long getColumnBitmask() {
        return _columnBitmask;
    }

    @Override
    public ExpandoBridge getExpandoBridge() {
        return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
            LFSocialPackageTag.class.getName(), getPrimaryKey());
    }

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
        ExpandoBridge expandoBridge = getExpandoBridge();

        expandoBridge.setAttributes(serviceContext);
    }

    @Override
    public LFSocialPackageTag toEscapedModel() {
        if (_escapedModel == null) {
            _escapedModel = (LFSocialPackageTag) ProxyUtil.newProxyInstance(_classLoader,
                    _escapedModelInterfaces, new AutoEscapeBeanHandler(this));
        }

        return _escapedModel;
    }

    @Override
    public Object clone() {
        LFSocialPackageTagImpl lfSocialPackageTagImpl = new LFSocialPackageTagImpl();

        lfSocialPackageTagImpl.setId(getId());
        lfSocialPackageTagImpl.setSocialPackageID(getSocialPackageID());
        lfSocialPackageTagImpl.setName(getName());

        lfSocialPackageTagImpl.resetOriginalValues();

        return lfSocialPackageTagImpl;
    }

    @Override
    public int compareTo(LFSocialPackageTag lfSocialPackageTag) {
        long primaryKey = lfSocialPackageTag.getPrimaryKey();

        if (getPrimaryKey() < primaryKey) {
            return -1;
        } else if (getPrimaryKey() > primaryKey) {
            return 1;
        } else {
            return 0;
        }
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }

        if (!(obj instanceof LFSocialPackageTag)) {
            return false;
        }

        LFSocialPackageTag lfSocialPackageTag = (LFSocialPackageTag) obj;

        long primaryKey = lfSocialPackageTag.getPrimaryKey();

        if (getPrimaryKey() == primaryKey) {
            return true;
        } else {
            return false;
        }
    }

    @Override
    public int hashCode() {
        return (int) getPrimaryKey();
    }

    @Override
    public void resetOriginalValues() {
        LFSocialPackageTagModelImpl lfSocialPackageTagModelImpl = this;

        lfSocialPackageTagModelImpl._originalSocialPackageID = lfSocialPackageTagModelImpl._socialPackageID;

        lfSocialPackageTagModelImpl._setOriginalSocialPackageID = false;

        lfSocialPackageTagModelImpl._originalName = lfSocialPackageTagModelImpl._name;

        lfSocialPackageTagModelImpl._columnBitmask = 0;
    }

    @Override
    public CacheModel<LFSocialPackageTag> toCacheModel() {
        LFSocialPackageTagCacheModel lfSocialPackageTagCacheModel = new LFSocialPackageTagCacheModel();

        lfSocialPackageTagCacheModel.id = getId();

        lfSocialPackageTagCacheModel.socialPackageID = getSocialPackageID();

        lfSocialPackageTagCacheModel.name = getName();

        String name = lfSocialPackageTagCacheModel.name;

        if ((name != null) && (name.length() == 0)) {
            lfSocialPackageTagCacheModel.name = null;
        }

        return lfSocialPackageTagCacheModel;
    }

    @Override
    public String toString() {
        StringBundler sb = new StringBundler(7);

        sb.append("{id=");
        sb.append(getId());
        sb.append(", socialPackageID=");
        sb.append(getSocialPackageID());
        sb.append(", name=");
        sb.append(getName());
        sb.append("}");

        return sb.toString();
    }

    @Override
    public String toXmlString() {
        StringBundler sb = new StringBundler(13);

        sb.append("<model><model-name>");
        sb.append(
            "com.arcusys.learn.persistence.liferay.model.LFSocialPackageTag");
        sb.append("</model-name>");

        sb.append(
            "<column><column-name>id</column-name><column-value><![CDATA[");
        sb.append(getId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>socialPackageID</column-name><column-value><![CDATA[");
        sb.append(getSocialPackageID());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>name</column-name><column-value><![CDATA[");
        sb.append(getName());
        sb.append("]]></column-value></column>");

        sb.append("</model>");

        return sb.toString();
    }
}
