package com.arcusys.learn.persistence.liferay.model.impl;

import com.arcusys.learn.persistence.liferay.model.LFTincanLrsAgentProfile;
import com.arcusys.learn.persistence.liferay.model.LFTincanLrsAgentProfileModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the LFTincanLrsAgentProfile service. Represents a row in the &quot;Learn_LFTincanLrsAgentProfile&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.arcusys.learn.persistence.liferay.model.LFTincanLrsAgentProfileModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LFTincanLrsAgentProfileImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LFTincanLrsAgentProfileImpl
 * @see com.arcusys.learn.persistence.liferay.model.LFTincanLrsAgentProfile
 * @see com.arcusys.learn.persistence.liferay.model.LFTincanLrsAgentProfileModel
 * @generated
 */
public class LFTincanLrsAgentProfileModelImpl extends BaseModelImpl<LFTincanLrsAgentProfile>
    implements LFTincanLrsAgentProfileModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a l f tincan lrs agent profile model instance should use the {@link com.arcusys.learn.persistence.liferay.model.LFTincanLrsAgentProfile} interface instead.
     */
    public static final String TABLE_NAME = "Learn_LFTincanLrsAgentProfile";
    public static final Object[][] TABLE_COLUMNS = {
            { "id_", Types.BIGINT },
            { "documentId", Types.INTEGER },
            { "agentId", Types.INTEGER },
            { "profileId", Types.VARCHAR }
        };
    public static final String TABLE_SQL_CREATE = "create table Learn_LFTincanLrsAgentProfile (id_ LONG not null primary key,documentId INTEGER null,agentId INTEGER null,profileId VARCHAR(75) null)";
    public static final String TABLE_SQL_DROP = "drop table Learn_LFTincanLrsAgentProfile";
    public static final String ORDER_BY_JPQL = " ORDER BY lfTincanLrsAgentProfile.id ASC";
    public static final String ORDER_BY_SQL = " ORDER BY Learn_LFTincanLrsAgentProfile.id_ ASC";
    public static final String DATA_SOURCE = "liferayDataSource";
    public static final String SESSION_FACTORY = "liferaySessionFactory";
    public static final String TX_MANAGER = "liferayTransactionManager";
    public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.entity.cache.enabled.com.arcusys.learn.persistence.liferay.model.LFTincanLrsAgentProfile"),
            false);
    public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.finder.cache.enabled.com.arcusys.learn.persistence.liferay.model.LFTincanLrsAgentProfile"),
            false);
    public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.column.bitmask.enabled.com.arcusys.learn.persistence.liferay.model.LFTincanLrsAgentProfile"),
            true);
    public static long AGENTID_COLUMN_BITMASK = 1L;
    public static long PROFILEID_COLUMN_BITMASK = 2L;
    public static long ID_COLUMN_BITMASK = 4L;
    public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
                "lock.expiration.time.com.arcusys.learn.persistence.liferay.model.LFTincanLrsAgentProfile"));
    private static ClassLoader _classLoader = LFTincanLrsAgentProfile.class.getClassLoader();
    private static Class<?>[] _escapedModelInterfaces = new Class[] {
            LFTincanLrsAgentProfile.class
        };
    private long _id;
    private Integer _documentId;
    private Integer _agentId;
    private Integer _originalAgentId;
    private boolean _setOriginalAgentId;
    private String _profileId;
    private String _originalProfileId;
    private long _columnBitmask;
    private LFTincanLrsAgentProfile _escapedModel;

    public LFTincanLrsAgentProfileModelImpl() {
    }

    @Override
    public long getPrimaryKey() {
        return _id;
    }

    @Override
    public void setPrimaryKey(long primaryKey) {
        setId(primaryKey);
    }

    @Override
    public Serializable getPrimaryKeyObj() {
        return _id;
    }

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj) {
        setPrimaryKey(((Long) primaryKeyObj).longValue());
    }

    @Override
    public Class<?> getModelClass() {
        return LFTincanLrsAgentProfile.class;
    }

    @Override
    public String getModelClassName() {
        return LFTincanLrsAgentProfile.class.getName();
    }

    @Override
    public Map<String, Object> getModelAttributes() {
        Map<String, Object> attributes = new HashMap<String, Object>();

        attributes.put("id", getId());
        attributes.put("documentId", getDocumentId());
        attributes.put("agentId", getAgentId());
        attributes.put("profileId", getProfileId());

        return attributes;
    }

    @Override
    public void setModelAttributes(Map<String, Object> attributes) {
        Long id = (Long) attributes.get("id");

        if (id != null) {
            setId(id);
        }

        Integer documentId = (Integer) attributes.get("documentId");

        if (documentId != null) {
            setDocumentId(documentId);
        }

        Integer agentId = (Integer) attributes.get("agentId");

        if (agentId != null) {
            setAgentId(agentId);
        }

        String profileId = (String) attributes.get("profileId");

        if (profileId != null) {
            setProfileId(profileId);
        }
    }

    @Override
    public long getId() {
        return _id;
    }

    @Override
    public void setId(long id) {
        _id = id;
    }

    @Override
    public Integer getDocumentId() {
        return _documentId;
    }

    @Override
    public void setDocumentId(Integer documentId) {
        _documentId = documentId;
    }

    @Override
    public Integer getAgentId() {
        return _agentId;
    }

    @Override
    public void setAgentId(Integer agentId) {
        _columnBitmask |= AGENTID_COLUMN_BITMASK;

        if (!_setOriginalAgentId) {
            _setOriginalAgentId = true;

            _originalAgentId = _agentId;
        }

        _agentId = agentId;
    }

    public Integer getOriginalAgentId() {
        return _originalAgentId;
    }

    @Override
    public String getProfileId() {
        return _profileId;
    }

    @Override
    public void setProfileId(String profileId) {
        _columnBitmask |= PROFILEID_COLUMN_BITMASK;

        if (_originalProfileId == null) {
            _originalProfileId = _profileId;
        }

        _profileId = profileId;
    }

    public String getOriginalProfileId() {
        return _originalProfileId;
    }

    public long getColumnBitmask() {
        return _columnBitmask;
    }

    @Override
    public ExpandoBridge getExpandoBridge() {
        return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
            LFTincanLrsAgentProfile.class.getName(), getPrimaryKey());
    }

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
        ExpandoBridge expandoBridge = getExpandoBridge();

        expandoBridge.setAttributes(serviceContext);
    }

    @Override
    public LFTincanLrsAgentProfile toEscapedModel() {
        if (_escapedModel == null) {
            _escapedModel = (LFTincanLrsAgentProfile) ProxyUtil.newProxyInstance(_classLoader,
                    _escapedModelInterfaces, new AutoEscapeBeanHandler(this));
        }

        return _escapedModel;
    }

    @Override
    public Object clone() {
        LFTincanLrsAgentProfileImpl lfTincanLrsAgentProfileImpl = new LFTincanLrsAgentProfileImpl();

        lfTincanLrsAgentProfileImpl.setId(getId());
        lfTincanLrsAgentProfileImpl.setDocumentId(getDocumentId());
        lfTincanLrsAgentProfileImpl.setAgentId(getAgentId());
        lfTincanLrsAgentProfileImpl.setProfileId(getProfileId());

        lfTincanLrsAgentProfileImpl.resetOriginalValues();

        return lfTincanLrsAgentProfileImpl;
    }

    @Override
    public int compareTo(LFTincanLrsAgentProfile lfTincanLrsAgentProfile) {
        long primaryKey = lfTincanLrsAgentProfile.getPrimaryKey();

        if (getPrimaryKey() < primaryKey) {
            return -1;
        } else if (getPrimaryKey() > primaryKey) {
            return 1;
        } else {
            return 0;
        }
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }

        if (!(obj instanceof LFTincanLrsAgentProfile)) {
            return false;
        }

        LFTincanLrsAgentProfile lfTincanLrsAgentProfile = (LFTincanLrsAgentProfile) obj;

        long primaryKey = lfTincanLrsAgentProfile.getPrimaryKey();

        if (getPrimaryKey() == primaryKey) {
            return true;
        } else {
            return false;
        }
    }

    @Override
    public int hashCode() {
        return (int) getPrimaryKey();
    }

    @Override
    public void resetOriginalValues() {
        LFTincanLrsAgentProfileModelImpl lfTincanLrsAgentProfileModelImpl = this;

        lfTincanLrsAgentProfileModelImpl._originalAgentId = lfTincanLrsAgentProfileModelImpl._agentId;

        lfTincanLrsAgentProfileModelImpl._setOriginalAgentId = false;

        lfTincanLrsAgentProfileModelImpl._originalProfileId = lfTincanLrsAgentProfileModelImpl._profileId;

        lfTincanLrsAgentProfileModelImpl._columnBitmask = 0;
    }

    @Override
    public CacheModel<LFTincanLrsAgentProfile> toCacheModel() {
        LFTincanLrsAgentProfileCacheModel lfTincanLrsAgentProfileCacheModel = new LFTincanLrsAgentProfileCacheModel();

        lfTincanLrsAgentProfileCacheModel.id = getId();

        lfTincanLrsAgentProfileCacheModel.documentId = getDocumentId();

        lfTincanLrsAgentProfileCacheModel.agentId = getAgentId();

        lfTincanLrsAgentProfileCacheModel.profileId = getProfileId();

        String profileId = lfTincanLrsAgentProfileCacheModel.profileId;

        if ((profileId != null) && (profileId.length() == 0)) {
            lfTincanLrsAgentProfileCacheModel.profileId = null;
        }

        return lfTincanLrsAgentProfileCacheModel;
    }

    @Override
    public String toString() {
        StringBundler sb = new StringBundler(9);

        sb.append("{id=");
        sb.append(getId());
        sb.append(", documentId=");
        sb.append(getDocumentId());
        sb.append(", agentId=");
        sb.append(getAgentId());
        sb.append(", profileId=");
        sb.append(getProfileId());
        sb.append("}");

        return sb.toString();
    }

    @Override
    public String toXmlString() {
        StringBundler sb = new StringBundler(16);

        sb.append("<model><model-name>");
        sb.append(
            "com.arcusys.learn.persistence.liferay.model.LFTincanLrsAgentProfile");
        sb.append("</model-name>");

        sb.append(
            "<column><column-name>id</column-name><column-value><![CDATA[");
        sb.append(getId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>documentId</column-name><column-value><![CDATA[");
        sb.append(getDocumentId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>agentId</column-name><column-value><![CDATA[");
        sb.append(getAgentId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>profileId</column-name><column-value><![CDATA[");
        sb.append(getProfileId());
        sb.append("]]></column-value></column>");

        sb.append("</model>");

        return sb.toString();
    }
}
