package com.arcusys.learn.persistence.liferay.model.impl;

import com.arcusys.learn.persistence.liferay.model.LFTincanLrsAgentProfile;
import com.arcusys.learn.persistence.liferay.service.LFTincanLrsAgentProfileLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the LFTincanLrsAgentProfile service. Represents a row in the &quot;Learn_LFTincanLrsAgentProfile&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LFTincanLrsAgentProfileImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LFTincanLrsAgentProfileImpl
 * @see com.arcusys.learn.persistence.liferay.model.LFTincanLrsAgentProfile
 * @generated
 */
public abstract class LFTincanLrsAgentProfileBaseImpl
    extends LFTincanLrsAgentProfileModelImpl implements LFTincanLrsAgentProfile {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a l f tincan lrs agent profile model instance should use the {@link LFTincanLrsAgentProfile} interface instead.
     */
    public void persist() throws SystemException {
        if (this.isNew()) {
            LFTincanLrsAgentProfileLocalServiceUtil.addLFTincanLrsAgentProfile(this);
        } else {
            LFTincanLrsAgentProfileLocalServiceUtil.updateLFTincanLrsAgentProfile(this);
        }
    }
}
