package com.arcusys.learn.persistence.liferay.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the LFPackageVote service. Represents a row in the &quot;Learn_LFPackageVote&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.arcusys.learn.persistence.liferay.model.impl.LFPackageVoteModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.arcusys.learn.persistence.liferay.model.impl.LFPackageVoteImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LFPackageVote
 * @see com.arcusys.learn.persistence.liferay.model.impl.LFPackageVoteImpl
 * @see com.arcusys.learn.persistence.liferay.model.impl.LFPackageVoteModelImpl
 * @generated
 */
public interface LFPackageVoteModel extends BaseModel<LFPackageVote> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a l f package vote model instance should use the {@link LFPackageVote} interface instead.
     */

    /**
     * Returns the primary key of this l f package vote.
     *
     * @return the primary key of this l f package vote
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this l f package vote.
     *
     * @param primaryKey the primary key of this l f package vote
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the ID of this l f package vote.
     *
     * @return the ID of this l f package vote
     */
    public long getId();

    /**
     * Sets the ID of this l f package vote.
     *
     * @param id the ID of this l f package vote
     */
    public void setId(long id);

    /**
     * Returns the user i d of this l f package vote.
     *
     * @return the user i d of this l f package vote
     */
    public Integer getUserID();

    /**
     * Sets the user i d of this l f package vote.
     *
     * @param userID the user i d of this l f package vote
     */
    public void setUserID(Integer userID);

    /**
     * Returns the social package i d of this l f package vote.
     *
     * @return the social package i d of this l f package vote
     */
    public Integer getSocialPackageID();

    /**
     * Sets the social package i d of this l f package vote.
     *
     * @param socialPackageID the social package i d of this l f package vote
     */
    public void setSocialPackageID(Integer socialPackageID);

    /**
     * Returns the vote value of this l f package vote.
     *
     * @return the vote value of this l f package vote
     */
    public Integer getVoteValue();

    /**
     * Sets the vote value of this l f package vote.
     *
     * @param voteValue the vote value of this l f package vote
     */
    public void setVoteValue(Integer voteValue);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(LFPackageVote lfPackageVote);

    @Override
    public int hashCode();

    @Override
    public CacheModel<LFPackageVote> toCacheModel();

    @Override
    public LFPackageVote toEscapedModel();

    @Override
    public LFPackageVote toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
