package com.arcusys.learn.persistence.liferay.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the LFRequiredActivity service. Represents a row in the &quot;Learn_LFRequiredActivity&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.arcusys.learn.persistence.liferay.model.impl.LFRequiredActivityModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.arcusys.learn.persistence.liferay.model.impl.LFRequiredActivityImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LFRequiredActivity
 * @see com.arcusys.learn.persistence.liferay.model.impl.LFRequiredActivityImpl
 * @see com.arcusys.learn.persistence.liferay.model.impl.LFRequiredActivityModelImpl
 * @generated
 */
public interface LFRequiredActivityModel extends BaseModel<LFRequiredActivity> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a l f required activity model instance should use the {@link LFRequiredActivity} interface instead.
     */

    /**
     * Returns the primary key of this l f required activity.
     *
     * @return the primary key of this l f required activity
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this l f required activity.
     *
     * @param primaryKey the primary key of this l f required activity
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the ID of this l f required activity.
     *
     * @return the ID of this l f required activity
     */
    public long getId();

    /**
     * Sets the ID of this l f required activity.
     *
     * @param id the ID of this l f required activity
     */
    public void setId(long id);

    /**
     * Returns the achievement ID of this l f required activity.
     *
     * @return the achievement ID of this l f required activity
     */
    public Integer getAchievementId();

    /**
     * Sets the achievement ID of this l f required activity.
     *
     * @param achievementId the achievement ID of this l f required activity
     */
    public void setAchievementId(Integer achievementId);

    /**
     * Returns the activity class name of this l f required activity.
     *
     * @return the activity class name of this l f required activity
     */
    @AutoEscape
    public String getActivityClassName();

    /**
     * Sets the activity class name of this l f required activity.
     *
     * @param activityClassName the activity class name of this l f required activity
     */
    public void setActivityClassName(String activityClassName);

    /**
     * Returns the number activities required of this l f required activity.
     *
     * @return the number activities required of this l f required activity
     */
    public Integer getNumberActivitiesRequired();

    /**
     * Sets the number activities required of this l f required activity.
     *
     * @param numberActivitiesRequired the number activities required of this l f required activity
     */
    public void setNumberActivitiesRequired(Integer numberActivitiesRequired);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(LFRequiredActivity lfRequiredActivity);

    @Override
    public int hashCode();

    @Override
    public CacheModel<LFRequiredActivity> toCacheModel();

    @Override
    public LFRequiredActivity toEscapedModel();

    @Override
    public LFRequiredActivity toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
