package com.arcusys.learn.persistence.liferay.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the LFTincanCtxActivities service. Represents a row in the &quot;Learn_LFTincanCtxActivities&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.arcusys.learn.persistence.liferay.model.impl.LFTincanCtxActivitiesModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.arcusys.learn.persistence.liferay.model.impl.LFTincanCtxActivitiesImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LFTincanCtxActivities
 * @see com.arcusys.learn.persistence.liferay.model.impl.LFTincanCtxActivitiesImpl
 * @see com.arcusys.learn.persistence.liferay.model.impl.LFTincanCtxActivitiesModelImpl
 * @generated
 */
public interface LFTincanCtxActivitiesModel extends BaseModel<LFTincanCtxActivities> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a l f tincan ctx activities model instance should use the {@link LFTincanCtxActivities} interface instead.
     */

    /**
     * Returns the primary key of this l f tincan ctx activities.
     *
     * @return the primary key of this l f tincan ctx activities
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this l f tincan ctx activities.
     *
     * @param primaryKey the primary key of this l f tincan ctx activities
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the ID of this l f tincan ctx activities.
     *
     * @return the ID of this l f tincan ctx activities
     */
    public long getId();

    /**
     * Sets the ID of this l f tincan ctx activities.
     *
     * @param id the ID of this l f tincan ctx activities
     */
    public void setId(long id);

    /**
     * Returns the parent of this l f tincan ctx activities.
     *
     * @return the parent of this l f tincan ctx activities
     */
    @AutoEscape
    public String getParent();

    /**
     * Sets the parent of this l f tincan ctx activities.
     *
     * @param parent the parent of this l f tincan ctx activities
     */
    public void setParent(String parent);

    /**
     * Returns the grouping of this l f tincan ctx activities.
     *
     * @return the grouping of this l f tincan ctx activities
     */
    @AutoEscape
    public String getGrouping();

    /**
     * Sets the grouping of this l f tincan ctx activities.
     *
     * @param grouping the grouping of this l f tincan ctx activities
     */
    public void setGrouping(String grouping);

    /**
     * Returns the category of this l f tincan ctx activities.
     *
     * @return the category of this l f tincan ctx activities
     */
    @AutoEscape
    public String getCategory();

    /**
     * Sets the category of this l f tincan ctx activities.
     *
     * @param category the category of this l f tincan ctx activities
     */
    public void setCategory(String category);

    /**
     * Returns the other of this l f tincan ctx activities.
     *
     * @return the other of this l f tincan ctx activities
     */
    @AutoEscape
    public String getOther();

    /**
     * Sets the other of this l f tincan ctx activities.
     *
     * @param other the other of this l f tincan ctx activities
     */
    public void setOther(String other);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(LFTincanCtxActivities lfTincanCtxActivities);

    @Override
    public int hashCode();

    @Override
    public CacheModel<LFTincanCtxActivities> toCacheModel();

    @Override
    public LFTincanCtxActivities toEscapedModel();

    @Override
    public LFTincanCtxActivities toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
