package com.arcusys.learn.persistence.liferay.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the LFTincanClientApiStorage service. Represents a row in the &quot;Learn_LFTincanClientApiStorage&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.arcusys.learn.persistence.liferay.model.impl.LFTincanClientApiStorageModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.arcusys.learn.persistence.liferay.model.impl.LFTincanClientApiStorageImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LFTincanClientApiStorage
 * @see com.arcusys.learn.persistence.liferay.model.impl.LFTincanClientApiStorageImpl
 * @see com.arcusys.learn.persistence.liferay.model.impl.LFTincanClientApiStorageModelImpl
 * @generated
 */
public interface LFTincanClientApiStorageModel extends BaseModel<LFTincanClientApiStorage> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a l f tincan client api storage model instance should use the {@link LFTincanClientApiStorage} interface instead.
     */

    /**
     * Returns the primary key of this l f tincan client api storage.
     *
     * @return the primary key of this l f tincan client api storage
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this l f tincan client api storage.
     *
     * @param primaryKey the primary key of this l f tincan client api storage
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the ID of this l f tincan client api storage.
     *
     * @return the ID of this l f tincan client api storage
     */
    public long getId();

    /**
     * Sets the ID of this l f tincan client api storage.
     *
     * @param id the ID of this l f tincan client api storage
     */
    public void setId(long id);

    /**
     * Returns the name of this l f tincan client api storage.
     *
     * @return the name of this l f tincan client api storage
     */
    @AutoEscape
    public String getName();

    /**
     * Sets the name of this l f tincan client api storage.
     *
     * @param name the name of this l f tincan client api storage
     */
    public void setName(String name);

    /**
     * Returns the description of this l f tincan client api storage.
     *
     * @return the description of this l f tincan client api storage
     */
    @AutoEscape
    public String getDescription();

    /**
     * Sets the description of this l f tincan client api storage.
     *
     * @param description the description of this l f tincan client api storage
     */
    public void setDescription(String description);

    /**
     * Returns the secret of this l f tincan client api storage.
     *
     * @return the secret of this l f tincan client api storage
     */
    @AutoEscape
    public String getSecret();

    /**
     * Sets the secret of this l f tincan client api storage.
     *
     * @param secret the secret of this l f tincan client api storage
     */
    public void setSecret(String secret);

    /**
     * Returns the url of this l f tincan client api storage.
     *
     * @return the url of this l f tincan client api storage
     */
    @AutoEscape
    public String getUrl();

    /**
     * Sets the url of this l f tincan client api storage.
     *
     * @param url the url of this l f tincan client api storage
     */
    public void setUrl(String url);

    /**
     * Returns the redirect url of this l f tincan client api storage.
     *
     * @return the redirect url of this l f tincan client api storage
     */
    @AutoEscape
    public String getRedirectUrl();

    /**
     * Sets the redirect url of this l f tincan client api storage.
     *
     * @param redirectUrl the redirect url of this l f tincan client api storage
     */
    public void setRedirectUrl(String redirectUrl);

    /**
     * Returns the scope of this l f tincan client api storage.
     *
     * @return the scope of this l f tincan client api storage
     */
    @AutoEscape
    public String getScope();

    /**
     * Sets the scope of this l f tincan client api storage.
     *
     * @param scope the scope of this l f tincan client api storage
     */
    public void setScope(String scope);

    /**
     * Returns the icon url of this l f tincan client api storage.
     *
     * @return the icon url of this l f tincan client api storage
     */
    @AutoEscape
    public String getIconUrl();

    /**
     * Sets the icon url of this l f tincan client api storage.
     *
     * @param iconUrl the icon url of this l f tincan client api storage
     */
    public void setIconUrl(String iconUrl);

    /**
     * Returns the token of this l f tincan client api storage.
     *
     * @return the token of this l f tincan client api storage
     */
    @AutoEscape
    public String getToken();

    /**
     * Sets the token of this l f tincan client api storage.
     *
     * @param token the token of this l f tincan client api storage
     */
    public void setToken(String token);

    /**
     * Returns the code of this l f tincan client api storage.
     *
     * @return the code of this l f tincan client api storage
     */
    @AutoEscape
    public String getCode();

    /**
     * Sets the code of this l f tincan client api storage.
     *
     * @param code the code of this l f tincan client api storage
     */
    public void setCode(String code);

    /**
     * Returns the issued at of this l f tincan client api storage.
     *
     * @return the issued at of this l f tincan client api storage
     */
    public Date getIssuedAt();

    /**
     * Sets the issued at of this l f tincan client api storage.
     *
     * @param issuedAt the issued at of this l f tincan client api storage
     */
    public void setIssuedAt(Date issuedAt);

    /**
     * Returns the expired in of this l f tincan client api storage.
     *
     * @return the expired in of this l f tincan client api storage
     */
    public Long getExpiredIn();

    /**
     * Sets the expired in of this l f tincan client api storage.
     *
     * @param expiredIn the expired in of this l f tincan client api storage
     */
    public void setExpiredIn(Long expiredIn);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(LFTincanClientApiStorage lfTincanClientApiStorage);

    @Override
    public int hashCode();

    @Override
    public CacheModel<LFTincanClientApiStorage> toCacheModel();

    @Override
    public LFTincanClientApiStorage toEscapedModel();

    @Override
    public LFTincanClientApiStorage toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
